- label: "Projects"
  controller: "projects"
- label: "Organisms(D)"
  controller: "organisms"
- label: "Samples"
  controller: "samples"
- label: "Sample Non-Tissues(D)"
  controller: "sample_non_tissues"
- label: "MHC"
  controller: "mhcs"
- label: "DNA"
  controller: "mt_dnas"
  sub_tabs:
  - label: "mtDNA"
    controller: "mt_dnas"
  - label: "DNA Results"
    controller: "dna_results"
  - label: "MT DNA SEQ"
    controller: "mt_dna_seqs"
- label: "Microsatellites"
  controller: "microsatellites"
  sub_tabs:
  - label: "Microsatellites"
    controller: "microsatellites"
  - label: "Horizontals"
    controller: "microsatellite_horizontals"
  - label: "Final Horizontals"
    controller: "microsatellite_final_horizontals"
- label: "Genders"
  controller: "genders"
- label: "Y Chromosomes"
  controller: "y_chromosomes"
- label: "Organism Field Definition"
  controller: "dynamic_attributes"
- label: "Shipping Materials"
  controller: "shippingmaterials"
- label: "Locality Type"
  controller: "locality_types"
- label: "Extraction Methods"
  controller: "extraction_methods"
- label: "Admin"
  controller: "users"
  sub_tabs:
  - label: "Users"
    controller: "users"
  - label: "Security Settings"
    controller: "security_settings"
