- label: "Main"
  controller: "projects"
  sub_tabs:
  - label: "Projects"
    controller: "projects"
  - label: "Organisms(D)"
    controller: "organisms"
  - label: "Samples"
    controller: "samples"
  - label: "Sample Non-Tissues(D)"
    controller: "sample_non_tissues"
- label: "Tests"  
  controller: "mhcs"
  sub_tabs:
  - label: "MHC"
    controller: "mhcs"
  - label: "DNA"
    controller: "mt_dnas"
  - label: "mtDNA"
    controller: "mt_dnas"
  - label: "mtDNA Final Horizontals"
    controller: "mt_dna_final_horizontals"
  - label: "DNA Results"
    controller: "dna_results"
  - label: "MT DNA SEQ"
    controller: "mt_dna_seqs"
- label: "Microsatellites"
  controller: "microsatellites"
  sub_tabs:
  - label: "Microsatellites"
    controller: "microsatellites"
  - label: "Horizontals"
    controller: "microsatellite_horizontals"
  - label: "Final Horizontals"
    controller: "microsatellite_final_horizontals"
- label: "Genders"
  controller: "genders"
  sub_tabs:
  - label: "Genders"
    controller: "genders"
  - label: "Gender Final Horizontals"
    controller: "gender_final_horizontals"
- label: "Y Chromosomes"
  controller: "y_chromosomes"
  sub_tabs:
  - label: "Y Chromosomes"
    controller: "y_chromosomes"
  - label: "Y Chromosomes Final"
    controller: "y_chromosome_final_horizontals"
- label: "Organism Field Definition"
  controller: "dynamic_attributes"
- label: "Shipping Materials"
  controller: "shippingmaterials"
- label: "Locality Type"
  controller: "locality_types"
- label: "Extraction Methods"
  controller: "extraction_methods"
- label: "Admin"
  controller: "users"
  sub_tabs:
  - label: "Users"
    controller: "users"
  - label: "Security Settings"
    controller: "security_settings"
