- label: "Start Here"
  controller: "projects"
  sub_tabs:
  - label: "Projects"
    controller: "projects"
  - label: "Security Settings"
    controller: "security_settings"
- label: "Organisms"
  controller: "organisms"
  sub_tabs:
  - label: "Organisms"
    controller: "organisms"
  - label: "Organism Field Definition"
    controller: "dynamic_attributes"
- label: "Samples"
  controller: "samples"
  sub_tabs:
  - label: "Sample Non-Tissues(Dynamic)"
    controller: "sample_non_tissues"
- label: "DNA"  
  	controller: "dna_results"
- label: "mtDNA"  
  	controller: "mt_dnas"
  sub_tabs:
  - label: "mtDNA"
    controller: "mt_dnas"
  - label: "mtDNA Final Horizontals"
    controller: "mt_dna_final_horizontals"
  - label: "mtDNA SEQ"
    controller: "mt_dna_seqs"
- label: "Genders"
  controller: "genders"
  sub_tabs:
  - label: "Genders"
    controller: "genders"
  - label: "Gender Final Horizontals"
    controller: "gender_final_horizontals"
- label: "Microsatellites"
  controller: "microsatellites"
  sub_tabs:
  - label: "Microsatellites"
    controller: "microsatellites"
  - label: "Horizontals"
    controller: "microsatellite_horizontals"
  - label: "Final Horizontals"
    controller: "microsatellite_final_horizontals"
- label: "MHC"
  controller: "mhcs"
  sub_tabs:
  - label: "MHC"
    controller: "mhcs"
  - label: "MHC Horizontal"
    controller: "mhc_final_horizontals"
  - label: "MHC SEQ"
    controller: "mhc_seqs" 
- label: "Y Chromosomes"
  controller: "y_chromosomes"
  sub_tabs:
  - label: "Y Chromosomes"
    controller: "y_chromosomes"
  - label: "Y Chromosomes Final"
    controller: "y_chromosome_final_horizontals"
  - label: "Y Chromsomes SEQ"
    controller: "y_chromosome_seqs"
- label: "Lookup Tables"
  controller: "shippingmaterials"
  sub_tabs:
  - label: "Shipping Materials"
    controller: "shippingmaterials"
  - label: "Locality Type"
    controller: "locality_types"
  - label: "Extraction Methods"
    controller: "extraction_methods"
  - label: "Tissue Types"
    controller: "tissue_types"
  - label: "Address Roles"
    controller: "roles"
- label: "Admin"
  controller: "users"
  sub_tabs:
  - label: "Users"
    controller: "users"
  - label: "Addresses"
    controller: "addresses"
- label: "Queries"
  controller: "query"
- label: "Help"
  controller: "videos"