# This file is auto-generated from the current state of the database. Instead of editing this file, 
# please use the migrations feature of Active Record to incrementally modify your database, and
# then regenerate this schema definition.
#
# Note that this schema.rb definition is the authoritative source for your database schema. If you need
# to create the application database on another system, you should be using db:schema:load, not running
# all the migrations from scratch. The latter is a flawed and unsustainable approach (the more migrations
# you'll amass, the slower it'll run and the greater likelihood for issues).
#
# It's strongly recommended to check this file into your version control system.

ActiveRecord::Schema.define(:version => 20090424143951) do

  create_table "addresses", :force => true do |t|
    t.integer  "user_id"
    t.string   "first_name"
    t.string   "last_name"
    t.string   "address1"
    t.string   "address2"
    t.string   "province"
    t.string   "postal"
    t.string   "phone"
    t.string   "mobile"
    t.string   "fax"
    t.string   "email"
    t.string   "payment_method"
    t.string   "credit_card"
    t.string   "purchase_order"
    t.string   "overdue"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.integer  "role_id"
  end

  create_table "attachments", :force => true do |t|
    t.string   "filename"
    t.integer  "size"
    t.integer  "attachable_id"
    t.string   "attachable_type"
    t.datetime "created_at"
  end

  create_table "country_orig", :force => true do |t|
  end

  create_table "data_queries", :force => true do |t|
    t.text     "data"
    t.integer  "project_id"
    t.string   "access_key"
    t.datetime "accessed_at"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "dna_results", :force => true do |t|
    t.integer "sample_id"
    t.integer "project_id"
    t.integer "prep_number"
    t.integer "extraction_number"
    t.string  "barcode"
    t.string  "plate"
    t.string  "position"
    t.string  "extraction_method"
    t.date    "extraction_date"
    t.string  "extractor"
    t.string  "extractor_comments"
    t.float   "fluoro_conc"
    t.float   "functional_conc"
    t.float   "pico_green_conc"
    t.string  "storage_building"
    t.string  "storage_room"
    t.string  "storage_freezer"
    t.string  "storage_box"
    t.string  "xy_position"
    t.boolean "dna_remaining"
    t.text    "comments"
    t.integer "extraction_method_id"
  end

  create_table "dynamic_attribute_values", :force => true do |t|
    t.integer  "dynamic_attribute_id"
    t.string   "owner_type"
    t.integer  "owner_id"
    t.integer  "integer_value"
    t.integer  "float_value",          :limit => 10, :precision => 10, :scale => 0
    t.text     "text_value"
    t.date     "date_value"
    t.datetime "timestamp_value"
  end

  add_index "dynamic_attribute_values", ["dynamic_attribute_id"], :name => "index_dynamic_attribute_values_on_dynamic_attribute_id"
  add_index "dynamic_attribute_values", ["owner_id"], :name => "index_dynamic_attribute_values_on_owner_id"
  add_index "dynamic_attribute_values", ["owner_type"], :name => "index_dynamic_attribute_values_on_owner_type"
  add_index "dynamic_attribute_values", ["owner_type", "owner_id"], :name => "index_dynamic_attribute_values_on_owner_type_and_owner_id"

  create_table "dynamic_attributes", :force => true do |t|
    t.string  "name"
    t.integer "dynamic_type_id"
    t.integer "dynamic_class_id"
    t.string  "scoper_type"
    t.integer "scoper_id"
    t.string  "owner_type"
  end

  add_index "dynamic_attributes", ["name"], :name => "index_dynamic_attributes_on_name"
  add_index "dynamic_attributes", ["dynamic_type_id"], :name => "index_dynamic_attributes_on_dynamic_type_id"
  add_index "dynamic_attributes", ["dynamic_class_id"], :name => "index_dynamic_attributes_on_dynamic_class_id"
  add_index "dynamic_attributes", ["owner_type"], :name => "index_dynamic_attributes_on_owner_type"

  create_table "dynamic_classes", :force => true do |t|
    t.string "name"
  end

  add_index "dynamic_classes", ["name"], :name => "index_dynamic_classes_on_name"

  create_table "dynamic_types", :force => true do |t|
    t.string "name"
    t.string "stored_in_field"
    t.string "description"
  end

  add_index "dynamic_types", ["name"], :name => "index_dynamic_types_on_name"

  create_table "extraction_methods", :force => true do |t|
    t.string "extraction_method_name"
    t.string "extraction_method_description"
  end

  create_table "gender_final_horizontals", :force => true do |t|
    t.integer "project_id"
    t.integer "organism_id"
    t.string  "organism_code"
    t.integer "gender"
  end

  create_table "gender_final_horizontals_1", :force => true do |t|
    t.integer "project_id"
    t.integer "organism_id"
    t.string  "organism_code", :limit => 128
    t.string  "1"
  end

  create_table "gender_final_horizontals_12", :force => true do |t|
    t.integer "project_id"
    t.integer "organism_id"
    t.string  "organism_code", :limit => 128
  end

  create_table "gender_final_horizontals_17", :force => true do |t|
    t.integer "project_id"
    t.integer "organism_id"
    t.string  "organism_code", :limit => 128
    t.string  "1"
  end

  create_table "gender_final_horizontals_2", :force => true do |t|
    t.integer "project_id"
    t.integer "organism_id"
    t.string  "organism_code", :limit => 128
  end

  create_table "gender_final_horizontals_20", :force => true do |t|
    t.integer "project_id"
    t.integer "organism_id"
    t.string  "organism_code", :limit => 128
    t.string  "1"
  end

  create_table "gender_final_horizontals_3", :force => true do |t|
    t.integer "project_id"
    t.integer "organism_id"
    t.string  "organism_code", :limit => 128
  end

  create_table "gender_final_horizontals_4", :force => true do |t|
    t.integer "project_id"
    t.integer "organism_id"
    t.string  "organism_code", :limit => 128
  end

  create_table "gender_final_horizontals_5", :force => true do |t|
    t.integer "project_id"
    t.integer "organism_id"
    t.string  "organism_code", :limit => 128
  end

  create_table "gender_final_horizontals_6", :force => true do |t|
    t.integer "project_id"
    t.integer "organism_id"
    t.string  "organism_code", :limit => 128
    t.string  "1"
  end

  create_table "gender_final_horizontals_7", :force => true do |t|
    t.integer "project_id"
    t.integer "organism_id"
    t.string  "organism_code", :limit => 128
  end

  create_table "gender_final_horizontals_9", :force => true do |t|
    t.integer "project_id"
    t.integer "organism_id"
    t.string  "organism_code", :limit => 128
    t.string  "1"
  end

  create_table "genders", :force => true do |t|
    t.integer "sample_id"
    t.integer "project_id"
    t.string  "gender"
    t.string  "gelNum"
    t.string  "wellNum"
    t.boolean "finalResult"
    t.string  "locus"
    t.text    "comments"
    t.integer "locu_id"
  end

  create_table "locality_types", :force => true do |t|
    t.string "locality_type_name"
    t.string "locality_type_desc"
  end

  create_table "locus", :force => true do |t|
    t.string   "locus"
    t.string   "region"
    t.string   "marker"
    t.string   "conditions_data"
    t.string   "pdf_name"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "mhc_final_horizontals", :force => true do |t|
    t.integer "project_id"
    t.integer "organism_id"
    t.string  "organism_code"
    t.integer "allelea"
    t.integer "alleleb"
  end

  create_table "mhc_final_horizontals_1", :force => true do |t|
    t.integer "project_id"
    t.integer "organism_id"
    t.string  "organism_code", :limit => 128
    t.string  "1a"
    t.string  "1b"
    t.string  "aa"
    t.string  "ab"
    t.string  "socola"
    t.string  "socolb"
  end

  create_table "mhc_final_horizontals_12", :force => true do |t|
    t.integer "project_id"
    t.integer "organism_id"
    t.string  "organism_code", :limit => 128
  end

  create_table "mhc_final_horizontals_17", :force => true do |t|
    t.integer "project_id"
    t.integer "organism_id"
    t.string  "organism_code", :limit => 128
    t.string  "1a"
    t.string  "1b"
    t.string  "aa"
    t.string  "ab"
    t.string  "socola"
    t.string  "socolb"
  end

  create_table "mhc_final_horizontals_2", :force => true do |t|
    t.integer "project_id"
    t.integer "organism_id"
    t.string  "organism_code", :limit => 128
  end

  create_table "mhc_final_horizontals_20", :force => true do |t|
    t.integer "project_id"
    t.integer "organism_id"
    t.string  "organism_code", :limit => 128
    t.string  "aa"
    t.string  "ab"
    t.string  "socola"
    t.string  "socolb"
  end

  create_table "mhc_final_horizontals_3", :force => true do |t|
    t.integer "project_id"
    t.integer "organism_id"
    t.string  "organism_code", :limit => 128
  end

  create_table "mhc_final_horizontals_4", :force => true do |t|
    t.integer "project_id"
    t.integer "organism_id"
    t.string  "organism_code", :limit => 128
  end

  create_table "mhc_final_horizontals_5", :force => true do |t|
    t.integer "project_id"
    t.integer "organism_id"
    t.string  "organism_code", :limit => 128
  end

  create_table "mhc_final_horizontals_6", :force => true do |t|
    t.integer "project_id"
    t.integer "organism_id"
    t.string  "organism_code", :limit => 128
    t.string  "1a"
    t.string  "1b"
    t.string  "aa"
    t.string  "ab"
    t.string  "socola"
    t.string  "socolb"
  end

  create_table "mhc_final_horizontals_7", :force => true do |t|
    t.integer "project_id"
    t.integer "organism_id"
    t.string  "organism_code", :limit => 128
  end

  create_table "mhc_final_horizontals_9", :force => true do |t|
    t.integer "project_id"
    t.integer "organism_id"
    t.string  "organism_code", :limit => 128
    t.string  "1a"
    t.string  "1b"
    t.string  "aa"
    t.string  "ab"
    t.string  "socola"
    t.string  "socolb"
  end

  create_table "mhc_seqs", :force => true do |t|
    t.integer "project_id"
    t.string  "locus"
    t.string  "allele"
    t.text    "sequence"
    t.string  "accession",  :limit => 30
  end

  create_table "mhcs", :force => true do |t|
    t.integer "sample_id"
    t.integer "project_id"
    t.string  "locus"
    t.string  "allele1"
    t.string  "allele2"
    t.string  "gelNum"
    t.string  "wellNum"
    t.boolean "finalResult"
    t.text    "comments"
    t.integer "locu_id"
  end

  create_table "microsatellite_final_horizontals", :force => true do |t|
    t.integer "project_id"
    t.integer "organism_id"
    t.string  "organism_code"
    t.integer "allelea"
    t.integer "alleleb"
  end

  create_table "microsatellite_final_horizontals_1", :force => true do |t|
    t.integer "project_id"
    t.integer "organism_id"
    t.string  "organism_code", :limit => 128
    t.integer "aeioua"
    t.integer "aeioub"
    t.integer "EV1Pma"
    t.integer "EV1Pmb"
    t.integer "EV37Mna"
    t.integer "EV37Mnb"
    t.integer "GATA028a"
    t.integer "GATA028b"
    t.integer "GT023a"
    t.integer "GT023b"
    t.integer "GT271a"
    t.integer "GT271b"
    t.integer "IGFa"
    t.integer "IGFb"
    t.integer "RW18a"
    t.integer "RW18b"
    t.integer "RW212a"
    t.integer "RW212b"
    t.integer "RW217a"
    t.integer "RW217b"
    t.integer "RW219a"
    t.integer "RW219b"
    t.integer "RW25a"
    t.integer "RW25b"
    t.integer "RW31a"
    t.integer "RW31b"
    t.integer "RW34a"
    t.integer "RW34b"
    t.integer "RW417a"
    t.integer "RW417b"
    t.integer "RW45a"
    t.integer "RW45b"
    t.integer "RW48a"
    t.integer "RW48b"
    t.integer "SAM25a"
    t.integer "SAM25b"
    t.integer "TR2F3a"
    t.integer "TR2F3b"
    t.integer "TR2G5a"
    t.integer "TR2G5b"
    t.integer "TR3A1a"
    t.integer "TR3A1b"
    t.integer "TR3F2a"
    t.integer "TR3F2b"
    t.integer "TR3F7a"
    t.integer "TR3F7b"
    t.integer "TR3G1a"
    t.integer "TR3G1b"
    t.integer "TR3G10a"
    t.integer "TR3G10b"
    t.integer "TR3G11a"
    t.integer "TR3G11b"
    t.integer "TR3G13a"
    t.integer "TR3G13b"
    t.integer "TR3G2a"
    t.integer "TR3G2b"
    t.integer "TR3G5a"
    t.integer "TR3G5b"
    t.integer "TR3G6a"
    t.integer "TR3G6b"
    t.integer "TR3H14a"
    t.integer "TR3H14b"
    t.integer "TR3H4a"
    t.integer "TR3H4b"
    t.integer "TV14a"
    t.integer "TV14b"
    t.integer "TV17a"
    t.integer "TV17b"
    t.integer "TV19a"
    t.integer "TV19b"
    t.integer "TV20a"
    t.integer "TV20b"
  end

  create_table "microsatellite_final_horizontals_12", :force => true do |t|
    t.integer "project_id"
    t.integer "organism_id"
    t.string  "organism_code", :limit => 128
    t.integer "EV1Pma"
    t.integer "EV1Pmb"
    t.integer "IGFa"
    t.integer "IGFb"
    t.integer "MK6a"
    t.integer "MK6b"
    t.integer "RW34a"
    t.integer "RW34b"
    t.integer "TV19a"
    t.integer "TV19b"
    t.integer "TV2a"
    t.integer "TV2b"
    t.integer "TV5a"
    t.integer "TV5b"
  end

  create_table "microsatellite_final_horizontals_17", :force => true do |t|
    t.integer "project_id"
    t.integer "organism_id"
    t.string  "organism_code", :limit => 128
  end

  create_table "microsatellite_final_horizontals_2", :force => true do |t|
    t.integer "project_id"
    t.integer "organism_id"
    t.string  "organism_code", :limit => 128
    t.integer "EV1Pma"
    t.integer "EV1Pmb"
    t.integer "EV37Mna"
    t.integer "EV37Mnb"
    t.integer "G10Aa"
    t.integer "G10Ab"
    t.integer "G10Ba"
    t.integer "G10Bb"
    t.integer "G10Ca"
    t.integer "G10Cb"
    t.integer "G10Da"
    t.integer "G10Db"
    t.integer "G10Ha"
    t.integer "G10Hb"
    t.integer "G10Ja"
    t.integer "G10Jb"
    t.integer "G10La"
    t.integer "G10Lb"
    t.integer "G10Ma"
    t.integer "G10Mb"
    t.integer "G10Pa"
    t.integer "G10Pb"
    t.integer "G10Ua"
    t.integer "G10Ub"
    t.integer "G10Xa"
    t.integer "G10Xb"
    t.integer "GATA028a"
    t.integer "GATA028b"
    t.integer "GT023a"
    t.integer "GT023b"
    t.integer "GT271a"
    t.integer "GT271b"
    t.integer "IGFa"
    t.integer "IGFb"
    t.integer "MSUT10a"
    t.integer "MSUT10b"
    t.integer "MSUT100a"
    t.integer "MSUT100b"
    t.integer "MSUT101a"
    t.integer "MSUT101b"
    t.integer "MSUT102a"
    t.integer "MSUT102b"
    t.integer "MSUT103a"
    t.integer "MSUT103b"
    t.integer "MSUT104a"
    t.integer "MSUT104b"
    t.integer "MSUT105a"
    t.integer "MSUT105b"
    t.integer "MSUT106a"
    t.integer "MSUT106b"
    t.integer "MSUT107a"
    t.integer "MSUT107b"
    t.integer "MSUT108a"
    t.integer "MSUT108b"
    t.integer "MSUT109a"
    t.integer "MSUT109b"
    t.integer "MSUT11a"
    t.integer "MSUT11b"
    t.integer "MSUT110a"
    t.integer "MSUT110b"
    t.integer "MSUT111a"
    t.integer "MSUT111b"
    t.integer "MSUT112a"
    t.integer "MSUT112b"
    t.integer "MSUT113a"
    t.integer "MSUT113b"
    t.integer "MSUT114a"
    t.integer "MSUT114b"
    t.integer "MSUT115a"
    t.integer "MSUT115b"
    t.integer "MSUT116a"
    t.integer "MSUT116b"
    t.integer "MSUT117a"
    t.integer "MSUT117b"
    t.integer "MSUT118a"
    t.integer "MSUT118b"
    t.integer "MSUT119a"
    t.integer "MSUT119b"
    t.integer "MSUT12a"
    t.integer "MSUT12b"
    t.integer "MSUT120a"
    t.integer "MSUT120b"
    t.integer "MSUT121a"
    t.integer "MSUT121b"
    t.integer "MSUT122a"
    t.integer "MSUT122b"
    t.integer "MSUT123a"
    t.integer "MSUT123b"
    t.integer "MSUT124a"
    t.integer "MSUT124b"
    t.integer "MSUT125a"
    t.integer "MSUT125b"
    t.integer "MSUT126a"
    t.integer "MSUT126b"
    t.integer "MSUT127a"
    t.integer "MSUT127b"
    t.integer "MSUT128a"
    t.integer "MSUT128b"
    t.integer "MSUT129a"
    t.integer "MSUT129b"
    t.integer "MSUT13a"
    t.integer "MSUT13b"
    t.integer "MSUT130a"
    t.integer "MSUT130b"
    t.integer "MSUT131a"
    t.integer "MSUT131b"
    t.integer "MSUT132a"
    t.integer "MSUT132b"
    t.integer "MSUT133a"
    t.integer "MSUT133b"
    t.integer "MSUT134a"
    t.integer "MSUT134b"
    t.integer "MSUT135a"
    t.integer "MSUT135b"
    t.integer "MSUT136a"
    t.integer "MSUT136b"
    t.integer "MSUT137a"
    t.integer "MSUT137b"
    t.integer "MSUT138a"
    t.integer "MSUT138b"
    t.integer "MSUT139a"
    t.integer "MSUT139b"
    t.integer "MSUT14a"
    t.integer "MSUT14b"
    t.integer "MSUT140a"
    t.integer "MSUT140b"
    t.integer "MSUT141a"
    t.integer "MSUT141b"
    t.integer "MSUT142a"
    t.integer "MSUT142b"
    t.integer "MSUT143a"
    t.integer "MSUT143b"
    t.integer "MSUT144a"
    t.integer "MSUT144b"
    t.integer "MSUT145a"
    t.integer "MSUT145b"
    t.integer "MSUT146a"
    t.integer "MSUT146b"
    t.integer "MSUT147a"
    t.integer "MSUT147b"
    t.integer "MSUT148a"
    t.integer "MSUT148b"
    t.integer "MSUT149a"
    t.integer "MSUT149b"
    t.integer "MSUT15a"
    t.integer "MSUT15b"
    t.integer "MSUT150a"
    t.integer "MSUT150b"
    t.integer "MSUT151a"
    t.integer "MSUT151b"
    t.integer "MSUT152a"
    t.integer "MSUT152b"
    t.integer "MSUT153a"
    t.integer "MSUT153b"
    t.integer "MSUT154a"
    t.integer "MSUT154b"
    t.integer "MSUT155a"
    t.integer "MSUT155b"
    t.integer "MSUT156a"
    t.integer "MSUT156b"
    t.integer "MSUT157a"
    t.integer "MSUT157b"
    t.integer "MSUT158a"
    t.integer "MSUT158b"
    t.integer "MSUT159a"
    t.integer "MSUT159b"
    t.integer "MSUT16a"
    t.integer "MSUT16b"
    t.integer "MSUT160a"
    t.integer "MSUT160b"
    t.integer "MSUT161a"
    t.integer "MSUT161b"
    t.integer "MSUT162a"
    t.integer "MSUT162b"
    t.integer "MSUT163a"
    t.integer "MSUT163b"
    t.integer "MSUT164a"
    t.integer "MSUT164b"
    t.integer "MSUT165a"
    t.integer "MSUT165b"
    t.integer "MSUT166a"
    t.integer "MSUT166b"
    t.integer "MSUT167a"
    t.integer "MSUT167b"
    t.integer "MSUT168a"
    t.integer "MSUT168b"
    t.integer "MSUT169a"
    t.integer "MSUT169b"
    t.integer "MSUT17a"
    t.integer "MSUT17b"
    t.integer "MSUT170a"
    t.integer "MSUT170b"
    t.integer "MSUT171a"
    t.integer "MSUT171b"
    t.integer "MSUT172a"
    t.integer "MSUT172b"
    t.integer "MSUT173a"
    t.integer "MSUT173b"
    t.integer "MSUT174a"
    t.integer "MSUT174b"
    t.integer "MSUT175a"
    t.integer "MSUT175b"
    t.integer "MSUT176a"
    t.integer "MSUT176b"
    t.integer "MSUT177a"
    t.integer "MSUT177b"
    t.integer "MSUT178a"
    t.integer "MSUT178b"
    t.integer "MSUT179a"
    t.integer "MSUT179b"
    t.integer "MSUT18a"
    t.integer "MSUT18b"
    t.integer "MSUT180a"
    t.integer "MSUT180b"
    t.integer "MSUT181a"
    t.integer "MSUT181b"
    t.integer "MSUT182a"
    t.integer "MSUT182b"
    t.integer "MSUT183a"
    t.integer "MSUT183b"
    t.integer "MSUT184a"
    t.integer "MSUT184b"
    t.integer "MSUT185a"
    t.integer "MSUT185b"
    t.integer "MSUT186a"
    t.integer "MSUT186b"
    t.integer "MSUT187a"
    t.integer "MSUT187b"
    t.integer "MSUT188a"
    t.integer "MSUT188b"
    t.integer "MSUT189a"
    t.integer "MSUT189b"
    t.integer "MSUT19a"
    t.integer "MSUT19b"
    t.integer "MSUT190a"
    t.integer "MSUT190b"
    t.integer "MSUT191a"
    t.integer "MSUT191b"
    t.integer "MSUT192a"
    t.integer "MSUT192b"
    t.integer "MSUT193a"
    t.integer "MSUT193b"
    t.integer "MSUT194a"
    t.integer "MSUT194b"
    t.integer "MSUT195a"
    t.integer "MSUT195b"
    t.integer "MSUT196a"
    t.integer "MSUT196b"
    t.integer "MSUT197a"
    t.integer "MSUT197b"
    t.integer "MSUT198a"
    t.integer "MSUT198b"
    t.integer "MSUT199a"
    t.integer "MSUT199b"
    t.integer "MSUT20a"
    t.integer "MSUT20b"
    t.integer "MSUT200a"
    t.integer "MSUT200b"
    t.integer "MSUT201a"
    t.integer "MSUT201b"
    t.integer "MSUT202a"
    t.integer "MSUT202b"
    t.integer "MSUT203a"
    t.integer "MSUT203b"
    t.integer "MSUT204a"
    t.integer "MSUT204b"
    t.integer "MSUT205a"
    t.integer "MSUT205b"
    t.integer "MSUT206a"
    t.integer "MSUT206b"
    t.integer "MSUT207a"
    t.integer "MSUT207b"
    t.integer "MSUT208a"
    t.integer "MSUT208b"
    t.integer "MSUT209a"
    t.integer "MSUT209b"
    t.integer "MSUT21a"
    t.integer "MSUT21b"
    t.integer "MSUT210a"
    t.integer "MSUT210b"
    t.integer "MSUT211a"
    t.integer "MSUT211b"
    t.integer "MSUT212a"
    t.integer "MSUT212b"
    t.integer "MSUT213a"
    t.integer "MSUT213b"
    t.integer "MSUT214a"
    t.integer "MSUT214b"
    t.integer "MSUT215a"
    t.integer "MSUT215b"
    t.integer "MSUT216a"
    t.integer "MSUT216b"
    t.integer "MSUT217a"
    t.integer "MSUT217b"
    t.integer "MSUT218a"
    t.integer "MSUT218b"
    t.integer "MSUT219a"
    t.integer "MSUT219b"
    t.integer "MSUT22a"
    t.integer "MSUT22b"
    t.integer "MSUT220a"
    t.integer "MSUT220b"
    t.integer "MSUT221a"
    t.integer "MSUT221b"
    t.integer "MSUT222a"
    t.integer "MSUT222b"
    t.integer "MSUT223a"
    t.integer "MSUT223b"
    t.integer "MSUT224a"
    t.integer "MSUT224b"
    t.integer "MSUT225a"
    t.integer "MSUT225b"
    t.integer "MSUT226a"
    t.integer "MSUT226b"
    t.integer "MSUT227a"
    t.integer "MSUT227b"
    t.integer "MSUT228a"
    t.integer "MSUT228b"
    t.integer "MSUT229a"
    t.integer "MSUT229b"
    t.integer "MSUT23a"
    t.integer "MSUT23b"
    t.integer "MSUT230a"
    t.integer "MSUT230b"
    t.integer "MSUT231a"
    t.integer "MSUT231b"
    t.integer "MSUT232a"
    t.integer "MSUT232b"
    t.integer "MSUT233a"
    t.integer "MSUT233b"
    t.integer "MSUT234a"
    t.integer "MSUT234b"
    t.integer "MSUT235a"
    t.integer "MSUT235b"
    t.integer "MSUT236a"
    t.integer "MSUT236b"
    t.integer "MSUT237a"
    t.integer "MSUT237b"
    t.integer "MSUT238a"
    t.integer "MSUT238b"
    t.integer "MSUT239a"
    t.integer "MSUT239b"
    t.integer "MSUT24a"
    t.integer "MSUT24b"
    t.integer "MSUT240a"
    t.integer "MSUT240b"
    t.integer "MSUT241a"
    t.integer "MSUT241b"
    t.integer "MSUT242a"
    t.integer "MSUT242b"
    t.integer "MSUT243a"
    t.integer "MSUT243b"
    t.integer "MSUT244a"
    t.integer "MSUT244b"
    t.integer "MSUT245a"
    t.integer "MSUT245b"
    t.integer "MSUT25a"
    t.integer "MSUT25b"
    t.integer "MSUT26a"
    t.integer "MSUT26b"
    t.integer "MSUT27a"
    t.integer "MSUT27b"
    t.integer "MSUT28a"
    t.integer "MSUT28b"
    t.integer "MSUT29a"
    t.integer "MSUT29b"
    t.integer "MSUT30a"
    t.integer "MSUT30b"
    t.integer "MSUT31a"
    t.integer "MSUT31b"
    t.integer "MSUT32a"
    t.integer "MSUT32b"
    t.integer "MSUT33a"
    t.integer "MSUT33b"
    t.integer "MSUT34a"
    t.integer "MSUT34b"
    t.integer "MSUT35a"
    t.integer "MSUT35b"
    t.integer "MSUT36a"
    t.integer "MSUT36b"
    t.integer "MSUT37a"
    t.integer "MSUT37b"
    t.integer "MSUT38a"
    t.integer "MSUT38b"
    t.integer "MSUT39a"
    t.integer "MSUT39b"
    t.integer "MSUT40a"
    t.integer "MSUT40b"
    t.integer "MSUT41a"
    t.integer "MSUT41b"
    t.integer "MSUT42a"
    t.integer "MSUT42b"
    t.integer "MSUT43a"
    t.integer "MSUT43b"
    t.integer "MSUT44a"
    t.integer "MSUT44b"
    t.integer "MSUT45a"
    t.integer "MSUT45b"
    t.integer "MSUT46a"
    t.integer "MSUT46b"
    t.integer "MSUT47a"
    t.integer "MSUT47b"
    t.integer "MSUT48a"
    t.integer "MSUT48b"
    t.integer "MSUT49a"
    t.integer "MSUT49b"
    t.integer "MSUT50a"
    t.integer "MSUT50b"
    t.integer "MSUT51a"
    t.integer "MSUT51b"
    t.integer "MSUT52a"
    t.integer "MSUT52b"
    t.integer "MSUT53a"
    t.integer "MSUT53b"
    t.integer "MSUT54a"
    t.integer "MSUT54b"
    t.integer "MSUT55a"
    t.integer "MSUT55b"
    t.integer "MSUT56a"
    t.integer "MSUT56b"
    t.integer "MSUT57a"
    t.integer "MSUT57b"
    t.integer "MSUT58a"
    t.integer "MSUT58b"
    t.integer "MSUT59a"
    t.integer "MSUT59b"
    t.integer "MSUT6a"
    t.integer "MSUT6b"
    t.integer "MSUT60a"
    t.integer "MSUT60b"
    t.integer "MSUT61a"
    t.integer "MSUT61b"
    t.integer "MSUT62a"
    t.integer "MSUT62b"
    t.integer "MSUT63a"
    t.integer "MSUT63b"
    t.integer "MSUT64a"
    t.integer "MSUT64b"
    t.integer "MSUT65a"
    t.integer "MSUT65b"
    t.integer "MSUT66a"
    t.integer "MSUT66b"
    t.integer "MSUT67a"
    t.integer "MSUT67b"
    t.integer "MSUT68a"
    t.integer "MSUT68b"
    t.integer "MSUT69a"
    t.integer "MSUT69b"
    t.integer "MSUT7a"
    t.integer "MSUT7b"
    t.integer "MSUT70a"
    t.integer "MSUT70b"
    t.integer "MSUT71a"
    t.integer "MSUT71b"
    t.integer "MSUT72a"
    t.integer "MSUT72b"
    t.integer "MSUT73a"
    t.integer "MSUT73b"
    t.integer "MSUT74a"
    t.integer "MSUT74b"
    t.integer "MSUT75a"
    t.integer "MSUT75b"
    t.integer "MSUT76a"
    t.integer "MSUT76b"
    t.integer "MSUT77a"
    t.integer "MSUT77b"
    t.integer "MSUT78a"
    t.integer "MSUT78b"
    t.integer "MSUT79a"
    t.integer "MSUT79b"
    t.integer "MSUT8a"
    t.integer "MSUT8b"
    t.integer "MSUT80a"
    t.integer "MSUT80b"
    t.integer "MSUT81a"
    t.integer "MSUT81b"
    t.integer "MSUT82a"
    t.integer "MSUT82b"
    t.integer "MSUT83a"
    t.integer "MSUT83b"
    t.integer "MSUT84a"
    t.integer "MSUT84b"
    t.integer "MSUT85a"
    t.integer "MSUT85b"
    t.integer "MSUT86a"
    t.integer "MSUT86b"
    t.integer "MSUT87a"
    t.integer "MSUT87b"
    t.integer "MSUT88a"
    t.integer "MSUT88b"
    t.integer "MSUT89a"
    t.integer "MSUT89b"
    t.integer "MSUT9a"
    t.integer "MSUT9b"
    t.integer "MSUT90a"
    t.integer "MSUT90b"
    t.integer "MSUT91a"
    t.integer "MSUT91b"
    t.integer "MSUT92a"
    t.integer "MSUT92b"
    t.integer "MSUT93a"
    t.integer "MSUT93b"
    t.integer "MSUT94a"
    t.integer "MSUT94b"
    t.integer "MSUT95a"
    t.integer "MSUT95b"
    t.integer "MSUT96a"
    t.integer "MSUT96b"
    t.integer "MSUT97a"
    t.integer "MSUT97b"
    t.integer "MSUT98a"
    t.integer "MSUT98b"
    t.integer "MSUT99a"
    t.integer "MSUT99b"
    t.integer "MU05a"
    t.integer "MU05b"
    t.integer "MU50a"
    t.integer "MU50b"
    t.integer "MU59a"
    t.integer "MU59b"
    t.integer "RW18a"
    t.integer "RW18b"
    t.integer "RW212a"
    t.integer "RW212b"
    t.integer "RW217a"
    t.integer "RW217b"
    t.integer "RW219a"
    t.integer "RW219b"
    t.integer "RW25a"
    t.integer "RW25b"
    t.integer "RW31a"
    t.integer "RW31b"
    t.integer "RW34a"
    t.integer "RW34b"
    t.integer "RW417a"
    t.integer "RW417b"
    t.integer "RW45a"
    t.integer "RW45b"
    t.integer "RW48a"
    t.integer "RW48b"
    t.integer "SAM25a"
    t.integer "SAM25b"
    t.integer "TR2F3a"
    t.integer "TR2F3b"
    t.integer "TR2G5a"
    t.integer "TR2G5b"
    t.integer "TR3A1a"
    t.integer "TR3A1b"
    t.integer "TR3F2a"
    t.integer "TR3F2b"
    t.integer "TR3F7a"
    t.integer "TR3F7b"
    t.integer "TR3G1a"
    t.integer "TR3G1b"
    t.integer "TR3G10a"
    t.integer "TR3G10b"
    t.integer "TR3G11a"
    t.integer "TR3G11b"
    t.integer "TR3G13a"
    t.integer "TR3G13b"
    t.integer "TR3G2a"
    t.integer "TR3G2b"
    t.integer "TR3G5a"
    t.integer "TR3G5b"
    t.integer "TR3G6a"
    t.integer "TR3G6b"
    t.integer "TR3H14a"
    t.integer "TR3H14b"
    t.integer "TR3H4a"
    t.integer "TR3H4b"
    t.integer "TV14a"
    t.integer "TV14b"
    t.integer "TV17a"
    t.integer "TV17b"
    t.integer "TV19a"
    t.integer "TV19b"
    t.integer "TV20a"
    t.integer "TV20b"
  end

  create_table "microsatellite_final_horizontals_20", :force => true do |t|
    t.integer "project_id"
    t.integer "organism_id"
    t.string  "organism_code", :limit => 128
    t.integer "-1a"
    t.integer "-1b"
    t.integer "Meatballa"
    t.integer "Meatballb"
    t.integer "Noodlea"
    t.integer "Noodleb"
    t.integer "nulla"
    t.integer "nullb"
    t.integer "zeroa"
    t.integer "zerob"
  end

  create_table "microsatellite_final_horizontals_3", :force => true do |t|
    t.integer "project_id"
    t.integer "organism_id"
    t.string  "organism_code", :limit => 128
    t.integer "Ms10a"
    t.integer "Ms10b"
    t.integer "Ms11a"
    t.integer "Ms11b"
    t.integer "Ms14a"
    t.integer "Ms14b"
    t.integer "Ms3a"
    t.integer "Ms3b"
    t.integer "Ms4a"
    t.integer "Ms4b"
    t.integer "Ms8a"
    t.integer "Ms8b"
  end

  create_table "microsatellite_final_horizontals_4", :force => true do |t|
    t.integer "project_id"
    t.integer "organism_id"
    t.string  "organism_code", :limit => 128
    t.integer "EV1Pma"
    t.integer "EV1Pmb"
    t.integer "EV37Mna"
    t.integer "EV37Mnb"
    t.integer "GATA028a"
    t.integer "GATA028b"
    t.integer "GT023a"
    t.integer "GT023b"
    t.integer "GT271a"
    t.integer "GT271b"
    t.integer "IGFa"
    t.integer "IGFb"
    t.integer "Ms10a"
    t.integer "Ms10b"
    t.integer "Ms11a"
    t.integer "Ms11b"
    t.integer "Ms14a"
    t.integer "Ms14b"
    t.integer "Ms3a"
    t.integer "Ms3b"
    t.integer "Ms4a"
    t.integer "Ms4b"
    t.integer "Ms8a"
    t.integer "Ms8b"
    t.integer "RW18a"
    t.integer "RW18b"
    t.integer "RW212a"
    t.integer "RW212b"
    t.integer "RW217a"
    t.integer "RW217b"
    t.integer "RW219a"
    t.integer "RW219b"
    t.integer "RW25a"
    t.integer "RW25b"
    t.integer "RW31a"
    t.integer "RW31b"
    t.integer "RW34a"
    t.integer "RW34b"
    t.integer "RW417a"
    t.integer "RW417b"
    t.integer "RW45a"
    t.integer "RW45b"
    t.integer "RW48a"
    t.integer "RW48b"
    t.integer "SAM25a"
    t.integer "SAM25b"
    t.integer "TR2F3a"
    t.integer "TR2F3b"
    t.integer "TR2G5a"
    t.integer "TR2G5b"
    t.integer "TR3A1a"
    t.integer "TR3A1b"
    t.integer "TR3F2a"
    t.integer "TR3F2b"
    t.integer "TR3F7a"
    t.integer "TR3F7b"
    t.integer "TR3G1a"
    t.integer "TR3G1b"
    t.integer "TR3G10a"
    t.integer "TR3G10b"
    t.integer "TR3G11a"
    t.integer "TR3G11b"
    t.integer "TR3G13a"
    t.integer "TR3G13b"
    t.integer "TR3G2a"
    t.integer "TR3G2b"
    t.integer "TR3G5a"
    t.integer "TR3G5b"
    t.integer "TR3G6a"
    t.integer "TR3G6b"
    t.integer "TR3H14a"
    t.integer "TR3H14b"
    t.integer "TR3H4a"
    t.integer "TR3H4b"
    t.integer "TV14a"
    t.integer "TV14b"
    t.integer "TV17a"
    t.integer "TV17b"
    t.integer "TV19a"
    t.integer "TV19b"
    t.integer "TV20a"
    t.integer "TV20b"
  end

  create_table "microsatellite_final_horizontals_5", :force => true do |t|
    t.integer "project_id"
    t.integer "organism_id"
    t.string  "organism_code", :limit => 128
  end

  create_table "microsatellite_final_horizontals_6", :force => true do |t|
    t.integer "project_id"
    t.integer "organism_id"
    t.string  "organism_code", :limit => 128
    t.integer "1a"
    t.integer "1b"
  end

  create_table "microsatellite_final_horizontals_7", :force => true do |t|
    t.integer "project_id"
    t.integer "organism_id"
    t.string  "organism_code", :limit => 128
    t.integer "109a"
    t.integer "109b"
    t.integer "123a"
    t.integer "123b"
    t.integer "172a"
    t.integer "172b"
    t.integer "200a"
    t.integer "200b"
    t.integer "204a"
    t.integer "204b"
    t.integer "225a"
    t.integer "225b"
    t.integer "250a"
    t.integer "250b"
    t.integer "377a"
    t.integer "377b"
  end

  create_table "microsatellite_final_horizontals_9", :force => true do |t|
    t.integer "project_id"
    t.integer "organism_id"
    t.string  "organism_code", :limit => 128
    t.integer "2a"
    t.integer "2b"
  end

  create_table "microsatellite_horizontals", :force => true do |t|
    t.integer "project_id"
    t.integer "sample_id"
    t.string  "organism_code"
    t.integer "org_sample"
    t.integer "allelea"
    t.integer "alleleb"
  end

  create_table "microsatellite_horizontals_1", :force => true do |t|
    t.integer "project_id"
    t.integer "sample_id"
    t.integer "organism_index"
    t.integer "aeioua"
    t.integer "aeioub"
    t.integer "EV1Pma"
    t.integer "EV1Pmb"
    t.integer "EV37Mna"
    t.integer "EV37Mnb"
    t.integer "GATA028a"
    t.integer "GATA028b"
    t.integer "GT023a"
    t.integer "GT023b"
    t.integer "GT271a"
    t.integer "GT271b"
    t.integer "IGFa"
    t.integer "IGFb"
    t.integer "RW18a"
    t.integer "RW18b"
    t.integer "RW212a"
    t.integer "RW212b"
    t.integer "RW217a"
    t.integer "RW217b"
    t.integer "RW219a"
    t.integer "RW219b"
    t.integer "RW25a"
    t.integer "RW25b"
    t.integer "RW31a"
    t.integer "RW31b"
    t.integer "RW34a"
    t.integer "RW34b"
    t.integer "RW417a"
    t.integer "RW417b"
    t.integer "RW45a"
    t.integer "RW45b"
    t.integer "RW48a"
    t.integer "RW48b"
    t.integer "SAM25a"
    t.integer "SAM25b"
    t.integer "TR2F3a"
    t.integer "TR2F3b"
    t.integer "TR2G5a"
    t.integer "TR2G5b"
    t.integer "TR3A1a"
    t.integer "TR3A1b"
    t.integer "TR3F2a"
    t.integer "TR3F2b"
    t.integer "TR3F7a"
    t.integer "TR3F7b"
    t.integer "TR3G1a"
    t.integer "TR3G1b"
    t.integer "TR3G10a"
    t.integer "TR3G10b"
    t.integer "TR3G11a"
    t.integer "TR3G11b"
    t.integer "TR3G13a"
    t.integer "TR3G13b"
    t.integer "TR3G2a"
    t.integer "TR3G2b"
    t.integer "TR3G5a"
    t.integer "TR3G5b"
    t.integer "TR3G6a"
    t.integer "TR3G6b"
    t.integer "TR3H14a"
    t.integer "TR3H14b"
    t.integer "TR3H4a"
    t.integer "TR3H4b"
    t.integer "TV14a"
    t.integer "TV14b"
    t.integer "TV17a"
    t.integer "TV17b"
    t.integer "TV19a"
    t.integer "TV19b"
    t.integer "TV20a"
    t.integer "TV20b"
  end

  create_table "microsatellite_horizontals_12", :force => true do |t|
    t.integer "project_id"
    t.integer "sample_id"
    t.integer "organism_index"
    t.integer "EV1Pma"
    t.integer "EV1Pmb"
    t.integer "IGFa"
    t.integer "IGFb"
    t.integer "MK6a"
    t.integer "MK6b"
    t.integer "RW34a"
    t.integer "RW34b"
    t.integer "TV19a"
    t.integer "TV19b"
    t.integer "TV2a"
    t.integer "TV2b"
    t.integer "TV5a"
    t.integer "TV5b"
  end

  create_table "microsatellite_horizontals_17", :force => true do |t|
    t.integer "project_id"
    t.integer "sample_id"
    t.integer "organism_index"
  end

  create_table "microsatellite_horizontals_2", :force => true do |t|
    t.integer "project_id"
    t.integer "sample_id"
    t.integer "organism_index"
    t.integer "EV1Pma"
    t.integer "EV1Pmb"
    t.integer "EV37Mna"
    t.integer "EV37Mnb"
    t.integer "G10Aa"
    t.integer "G10Ab"
    t.integer "G10Ba"
    t.integer "G10Bb"
    t.integer "G10Ca"
    t.integer "G10Cb"
    t.integer "G10Da"
    t.integer "G10Db"
    t.integer "G10Ha"
    t.integer "G10Hb"
    t.integer "G10Ja"
    t.integer "G10Jb"
    t.integer "G10La"
    t.integer "G10Lb"
    t.integer "G10Ma"
    t.integer "G10Mb"
    t.integer "G10Pa"
    t.integer "G10Pb"
    t.integer "G10Ua"
    t.integer "G10Ub"
    t.integer "G10Xa"
    t.integer "G10Xb"
    t.integer "GATA028a"
    t.integer "GATA028b"
    t.integer "GT023a"
    t.integer "GT023b"
    t.integer "GT271a"
    t.integer "GT271b"
    t.integer "IGFa"
    t.integer "IGFb"
    t.integer "MSUT10a"
    t.integer "MSUT10b"
    t.integer "MSUT100a"
    t.integer "MSUT100b"
    t.integer "MSUT101a"
    t.integer "MSUT101b"
    t.integer "MSUT102a"
    t.integer "MSUT102b"
    t.integer "MSUT103a"
    t.integer "MSUT103b"
    t.integer "MSUT104a"
    t.integer "MSUT104b"
    t.integer "MSUT105a"
    t.integer "MSUT105b"
    t.integer "MSUT106a"
    t.integer "MSUT106b"
    t.integer "MSUT107a"
    t.integer "MSUT107b"
    t.integer "MSUT108a"
    t.integer "MSUT108b"
    t.integer "MSUT109a"
    t.integer "MSUT109b"
    t.integer "MSUT11a"
    t.integer "MSUT11b"
    t.integer "MSUT110a"
    t.integer "MSUT110b"
    t.integer "MSUT111a"
    t.integer "MSUT111b"
    t.integer "MSUT112a"
    t.integer "MSUT112b"
    t.integer "MSUT113a"
    t.integer "MSUT113b"
    t.integer "MSUT114a"
    t.integer "MSUT114b"
    t.integer "MSUT115a"
    t.integer "MSUT115b"
    t.integer "MSUT116a"
    t.integer "MSUT116b"
    t.integer "MSUT117a"
    t.integer "MSUT117b"
    t.integer "MSUT118a"
    t.integer "MSUT118b"
    t.integer "MSUT119a"
    t.integer "MSUT119b"
    t.integer "MSUT12a"
    t.integer "MSUT12b"
    t.integer "MSUT120a"
    t.integer "MSUT120b"
    t.integer "MSUT121a"
    t.integer "MSUT121b"
    t.integer "MSUT122a"
    t.integer "MSUT122b"
    t.integer "MSUT123a"
    t.integer "MSUT123b"
    t.integer "MSUT124a"
    t.integer "MSUT124b"
    t.integer "MSUT125a"
    t.integer "MSUT125b"
    t.integer "MSUT126a"
    t.integer "MSUT126b"
    t.integer "MSUT127a"
    t.integer "MSUT127b"
    t.integer "MSUT128a"
    t.integer "MSUT128b"
    t.integer "MSUT129a"
    t.integer "MSUT129b"
    t.integer "MSUT13a"
    t.integer "MSUT13b"
    t.integer "MSUT130a"
    t.integer "MSUT130b"
    t.integer "MSUT131a"
    t.integer "MSUT131b"
    t.integer "MSUT132a"
    t.integer "MSUT132b"
    t.integer "MSUT133a"
    t.integer "MSUT133b"
    t.integer "MSUT134a"
    t.integer "MSUT134b"
    t.integer "MSUT135a"
    t.integer "MSUT135b"
    t.integer "MSUT136a"
    t.integer "MSUT136b"
    t.integer "MSUT137a"
    t.integer "MSUT137b"
    t.integer "MSUT138a"
    t.integer "MSUT138b"
    t.integer "MSUT139a"
    t.integer "MSUT139b"
    t.integer "MSUT14a"
    t.integer "MSUT14b"
    t.integer "MSUT140a"
    t.integer "MSUT140b"
    t.integer "MSUT141a"
    t.integer "MSUT141b"
    t.integer "MSUT142a"
    t.integer "MSUT142b"
    t.integer "MSUT143a"
    t.integer "MSUT143b"
    t.integer "MSUT144a"
    t.integer "MSUT144b"
    t.integer "MSUT145a"
    t.integer "MSUT145b"
    t.integer "MSUT146a"
    t.integer "MSUT146b"
    t.integer "MSUT147a"
    t.integer "MSUT147b"
    t.integer "MSUT148a"
    t.integer "MSUT148b"
    t.integer "MSUT149a"
    t.integer "MSUT149b"
    t.integer "MSUT15a"
    t.integer "MSUT15b"
    t.integer "MSUT150a"
    t.integer "MSUT150b"
    t.integer "MSUT151a"
    t.integer "MSUT151b"
    t.integer "MSUT152a"
    t.integer "MSUT152b"
    t.integer "MSUT153a"
    t.integer "MSUT153b"
    t.integer "MSUT154a"
    t.integer "MSUT154b"
    t.integer "MSUT155a"
    t.integer "MSUT155b"
    t.integer "MSUT156a"
    t.integer "MSUT156b"
    t.integer "MSUT157a"
    t.integer "MSUT157b"
    t.integer "MSUT158a"
    t.integer "MSUT158b"
    t.integer "MSUT159a"
    t.integer "MSUT159b"
    t.integer "MSUT16a"
    t.integer "MSUT16b"
    t.integer "MSUT160a"
    t.integer "MSUT160b"
    t.integer "MSUT161a"
    t.integer "MSUT161b"
    t.integer "MSUT162a"
    t.integer "MSUT162b"
    t.integer "MSUT163a"
    t.integer "MSUT163b"
    t.integer "MSUT164a"
    t.integer "MSUT164b"
    t.integer "MSUT165a"
    t.integer "MSUT165b"
    t.integer "MSUT166a"
    t.integer "MSUT166b"
    t.integer "MSUT167a"
    t.integer "MSUT167b"
    t.integer "MSUT168a"
    t.integer "MSUT168b"
    t.integer "MSUT169a"
    t.integer "MSUT169b"
    t.integer "MSUT17a"
    t.integer "MSUT17b"
    t.integer "MSUT170a"
    t.integer "MSUT170b"
    t.integer "MSUT171a"
    t.integer "MSUT171b"
    t.integer "MSUT172a"
    t.integer "MSUT172b"
    t.integer "MSUT173a"
    t.integer "MSUT173b"
    t.integer "MSUT174a"
    t.integer "MSUT174b"
    t.integer "MSUT175a"
    t.integer "MSUT175b"
    t.integer "MSUT176a"
    t.integer "MSUT176b"
    t.integer "MSUT177a"
    t.integer "MSUT177b"
    t.integer "MSUT178a"
    t.integer "MSUT178b"
    t.integer "MSUT179a"
    t.integer "MSUT179b"
    t.integer "MSUT18a"
    t.integer "MSUT18b"
    t.integer "MSUT180a"
    t.integer "MSUT180b"
    t.integer "MSUT181a"
    t.integer "MSUT181b"
    t.integer "MSUT182a"
    t.integer "MSUT182b"
    t.integer "MSUT183a"
    t.integer "MSUT183b"
    t.integer "MSUT184a"
    t.integer "MSUT184b"
    t.integer "MSUT185a"
    t.integer "MSUT185b"
    t.integer "MSUT186a"
    t.integer "MSUT186b"
    t.integer "MSUT187a"
    t.integer "MSUT187b"
    t.integer "MSUT188a"
    t.integer "MSUT188b"
    t.integer "MSUT189a"
    t.integer "MSUT189b"
    t.integer "MSUT19a"
    t.integer "MSUT19b"
    t.integer "MSUT190a"
    t.integer "MSUT190b"
    t.integer "MSUT191a"
    t.integer "MSUT191b"
    t.integer "MSUT192a"
    t.integer "MSUT192b"
    t.integer "MSUT193a"
    t.integer "MSUT193b"
    t.integer "MSUT194a"
    t.integer "MSUT194b"
    t.integer "MSUT195a"
    t.integer "MSUT195b"
    t.integer "MSUT196a"
    t.integer "MSUT196b"
    t.integer "MSUT197a"
    t.integer "MSUT197b"
    t.integer "MSUT198a"
    t.integer "MSUT198b"
    t.integer "MSUT199a"
    t.integer "MSUT199b"
    t.integer "MSUT20a"
    t.integer "MSUT20b"
    t.integer "MSUT200a"
    t.integer "MSUT200b"
    t.integer "MSUT201a"
    t.integer "MSUT201b"
    t.integer "MSUT202a"
    t.integer "MSUT202b"
    t.integer "MSUT203a"
    t.integer "MSUT203b"
    t.integer "MSUT204a"
    t.integer "MSUT204b"
    t.integer "MSUT205a"
    t.integer "MSUT205b"
    t.integer "MSUT206a"
    t.integer "MSUT206b"
    t.integer "MSUT207a"
    t.integer "MSUT207b"
    t.integer "MSUT208a"
    t.integer "MSUT208b"
    t.integer "MSUT209a"
    t.integer "MSUT209b"
    t.integer "MSUT21a"
    t.integer "MSUT21b"
    t.integer "MSUT210a"
    t.integer "MSUT210b"
    t.integer "MSUT211a"
    t.integer "MSUT211b"
    t.integer "MSUT212a"
    t.integer "MSUT212b"
    t.integer "MSUT213a"
    t.integer "MSUT213b"
    t.integer "MSUT214a"
    t.integer "MSUT214b"
    t.integer "MSUT215a"
    t.integer "MSUT215b"
    t.integer "MSUT216a"
    t.integer "MSUT216b"
    t.integer "MSUT217a"
    t.integer "MSUT217b"
    t.integer "MSUT218a"
    t.integer "MSUT218b"
    t.integer "MSUT219a"
    t.integer "MSUT219b"
    t.integer "MSUT22a"
    t.integer "MSUT22b"
    t.integer "MSUT220a"
    t.integer "MSUT220b"
    t.integer "MSUT221a"
    t.integer "MSUT221b"
    t.integer "MSUT222a"
    t.integer "MSUT222b"
    t.integer "MSUT223a"
    t.integer "MSUT223b"
    t.integer "MSUT224a"
    t.integer "MSUT224b"
    t.integer "MSUT225a"
    t.integer "MSUT225b"
    t.integer "MSUT226a"
    t.integer "MSUT226b"
    t.integer "MSUT227a"
    t.integer "MSUT227b"
    t.integer "MSUT228a"
    t.integer "MSUT228b"
    t.integer "MSUT229a"
    t.integer "MSUT229b"
    t.integer "MSUT23a"
    t.integer "MSUT23b"
    t.integer "MSUT230a"
    t.integer "MSUT230b"
    t.integer "MSUT231a"
    t.integer "MSUT231b"
    t.integer "MSUT232a"
    t.integer "MSUT232b"
    t.integer "MSUT233a"
    t.integer "MSUT233b"
    t.integer "MSUT234a"
    t.integer "MSUT234b"
    t.integer "MSUT235a"
    t.integer "MSUT235b"
    t.integer "MSUT236a"
    t.integer "MSUT236b"
    t.integer "MSUT237a"
    t.integer "MSUT237b"
    t.integer "MSUT238a"
    t.integer "MSUT238b"
    t.integer "MSUT239a"
    t.integer "MSUT239b"
    t.integer "MSUT24a"
    t.integer "MSUT24b"
    t.integer "MSUT240a"
    t.integer "MSUT240b"
    t.integer "MSUT241a"
    t.integer "MSUT241b"
    t.integer "MSUT242a"
    t.integer "MSUT242b"
    t.integer "MSUT243a"
    t.integer "MSUT243b"
    t.integer "MSUT244a"
    t.integer "MSUT244b"
    t.integer "MSUT245a"
    t.integer "MSUT245b"
    t.integer "MSUT25a"
    t.integer "MSUT25b"
    t.integer "MSUT26a"
    t.integer "MSUT26b"
    t.integer "MSUT27a"
    t.integer "MSUT27b"
    t.integer "MSUT28a"
    t.integer "MSUT28b"
    t.integer "MSUT29a"
    t.integer "MSUT29b"
    t.integer "MSUT30a"
    t.integer "MSUT30b"
    t.integer "MSUT31a"
    t.integer "MSUT31b"
    t.integer "MSUT32a"
    t.integer "MSUT32b"
    t.integer "MSUT33a"
    t.integer "MSUT33b"
    t.integer "MSUT34a"
    t.integer "MSUT34b"
    t.integer "MSUT35a"
    t.integer "MSUT35b"
    t.integer "MSUT36a"
    t.integer "MSUT36b"
    t.integer "MSUT37a"
    t.integer "MSUT37b"
    t.integer "MSUT38a"
    t.integer "MSUT38b"
    t.integer "MSUT39a"
    t.integer "MSUT39b"
    t.integer "MSUT40a"
    t.integer "MSUT40b"
    t.integer "MSUT41a"
    t.integer "MSUT41b"
    t.integer "MSUT42a"
    t.integer "MSUT42b"
    t.integer "MSUT43a"
    t.integer "MSUT43b"
    t.integer "MSUT44a"
    t.integer "MSUT44b"
    t.integer "MSUT45a"
    t.integer "MSUT45b"
    t.integer "MSUT46a"
    t.integer "MSUT46b"
    t.integer "MSUT47a"
    t.integer "MSUT47b"
    t.integer "MSUT48a"
    t.integer "MSUT48b"
    t.integer "MSUT49a"
    t.integer "MSUT49b"
    t.integer "MSUT50a"
    t.integer "MSUT50b"
    t.integer "MSUT51a"
    t.integer "MSUT51b"
    t.integer "MSUT52a"
    t.integer "MSUT52b"
    t.integer "MSUT53a"
    t.integer "MSUT53b"
    t.integer "MSUT54a"
    t.integer "MSUT54b"
    t.integer "MSUT55a"
    t.integer "MSUT55b"
    t.integer "MSUT56a"
    t.integer "MSUT56b"
    t.integer "MSUT57a"
    t.integer "MSUT57b"
    t.integer "MSUT58a"
    t.integer "MSUT58b"
    t.integer "MSUT59a"
    t.integer "MSUT59b"
    t.integer "MSUT6a"
    t.integer "MSUT6b"
    t.integer "MSUT60a"
    t.integer "MSUT60b"
    t.integer "MSUT61a"
    t.integer "MSUT61b"
    t.integer "MSUT62a"
    t.integer "MSUT62b"
    t.integer "MSUT63a"
    t.integer "MSUT63b"
    t.integer "MSUT64a"
    t.integer "MSUT64b"
    t.integer "MSUT65a"
    t.integer "MSUT65b"
    t.integer "MSUT66a"
    t.integer "MSUT66b"
    t.integer "MSUT67a"
    t.integer "MSUT67b"
    t.integer "MSUT68a"
    t.integer "MSUT68b"
    t.integer "MSUT69a"
    t.integer "MSUT69b"
    t.integer "MSUT7a"
    t.integer "MSUT7b"
    t.integer "MSUT70a"
    t.integer "MSUT70b"
    t.integer "MSUT71a"
    t.integer "MSUT71b"
    t.integer "MSUT72a"
    t.integer "MSUT72b"
    t.integer "MSUT73a"
    t.integer "MSUT73b"
    t.integer "MSUT74a"
    t.integer "MSUT74b"
    t.integer "MSUT75a"
    t.integer "MSUT75b"
    t.integer "MSUT76a"
    t.integer "MSUT76b"
    t.integer "MSUT77a"
    t.integer "MSUT77b"
    t.integer "MSUT78a"
    t.integer "MSUT78b"
    t.integer "MSUT79a"
    t.integer "MSUT79b"
    t.integer "MSUT8a"
    t.integer "MSUT8b"
    t.integer "MSUT80a"
    t.integer "MSUT80b"
    t.integer "MSUT81a"
    t.integer "MSUT81b"
    t.integer "MSUT82a"
    t.integer "MSUT82b"
    t.integer "MSUT83a"
    t.integer "MSUT83b"
    t.integer "MSUT84a"
    t.integer "MSUT84b"
    t.integer "MSUT85a"
    t.integer "MSUT85b"
    t.integer "MSUT86a"
    t.integer "MSUT86b"
    t.integer "MSUT87a"
    t.integer "MSUT87b"
    t.integer "MSUT88a"
    t.integer "MSUT88b"
    t.integer "MSUT89a"
    t.integer "MSUT89b"
    t.integer "MSUT9a"
    t.integer "MSUT9b"
    t.integer "MSUT90a"
    t.integer "MSUT90b"
    t.integer "MSUT91a"
    t.integer "MSUT91b"
    t.integer "MSUT92a"
    t.integer "MSUT92b"
    t.integer "MSUT93a"
    t.integer "MSUT93b"
    t.integer "MSUT94a"
    t.integer "MSUT94b"
    t.integer "MSUT95a"
    t.integer "MSUT95b"
    t.integer "MSUT96a"
    t.integer "MSUT96b"
    t.integer "MSUT97a"
    t.integer "MSUT97b"
    t.integer "MSUT98a"
    t.integer "MSUT98b"
    t.integer "MSUT99a"
    t.integer "MSUT99b"
    t.integer "MU05a"
    t.integer "MU05b"
    t.integer "MU50a"
    t.integer "MU50b"
    t.integer "MU59a"
    t.integer "MU59b"
    t.integer "RW18a"
    t.integer "RW18b"
    t.integer "RW212a"
    t.integer "RW212b"
    t.integer "RW217a"
    t.integer "RW217b"
    t.integer "RW219a"
    t.integer "RW219b"
    t.integer "RW25a"
    t.integer "RW25b"
    t.integer "RW31a"
    t.integer "RW31b"
    t.integer "RW34a"
    t.integer "RW34b"
    t.integer "RW417a"
    t.integer "RW417b"
    t.integer "RW45a"
    t.integer "RW45b"
    t.integer "RW48a"
    t.integer "RW48b"
    t.integer "SAM25a"
    t.integer "SAM25b"
    t.integer "TR2F3a"
    t.integer "TR2F3b"
    t.integer "TR2G5a"
    t.integer "TR2G5b"
    t.integer "TR3A1a"
    t.integer "TR3A1b"
    t.integer "TR3F2a"
    t.integer "TR3F2b"
    t.integer "TR3F7a"
    t.integer "TR3F7b"
    t.integer "TR3G1a"
    t.integer "TR3G1b"
    t.integer "TR3G10a"
    t.integer "TR3G10b"
    t.integer "TR3G11a"
    t.integer "TR3G11b"
    t.integer "TR3G13a"
    t.integer "TR3G13b"
    t.integer "TR3G2a"
    t.integer "TR3G2b"
    t.integer "TR3G5a"
    t.integer "TR3G5b"
    t.integer "TR3G6a"
    t.integer "TR3G6b"
    t.integer "TR3H14a"
    t.integer "TR3H14b"
    t.integer "TR3H4a"
    t.integer "TR3H4b"
    t.integer "TV14a"
    t.integer "TV14b"
    t.integer "TV17a"
    t.integer "TV17b"
    t.integer "TV19a"
    t.integer "TV19b"
    t.integer "TV20a"
    t.integer "TV20b"
  end

  create_table "microsatellite_horizontals_20", :force => true do |t|
    t.integer "project_id"
    t.integer "sample_id"
    t.integer "organism_index"
    t.integer "-1a"
    t.integer "-1b"
    t.integer "Meatballa"
    t.integer "Meatballb"
    t.integer "Noodlea"
    t.integer "Noodleb"
    t.integer "nulla"
    t.integer "nullb"
    t.integer "zeroa"
    t.integer "zerob"
  end

  create_table "microsatellite_horizontals_3", :force => true do |t|
    t.integer "project_id"
    t.integer "sample_id"
    t.integer "organism_index"
    t.integer "Ms10a"
    t.integer "Ms10b"
    t.integer "Ms11a"
    t.integer "Ms11b"
    t.integer "Ms14a"
    t.integer "Ms14b"
    t.integer "Ms3a"
    t.integer "Ms3b"
    t.integer "Ms4a"
    t.integer "Ms4b"
    t.integer "Ms8a"
    t.integer "Ms8b"
  end

  create_table "microsatellite_horizontals_4", :force => true do |t|
    t.integer "project_id"
    t.integer "sample_id"
    t.integer "organism_index"
    t.integer "EV1Pma"
    t.integer "EV1Pmb"
    t.integer "EV37Mna"
    t.integer "EV37Mnb"
    t.integer "GATA028a"
    t.integer "GATA028b"
    t.integer "GT023a"
    t.integer "GT023b"
    t.integer "GT271a"
    t.integer "GT271b"
    t.integer "IGFa"
    t.integer "IGFb"
    t.integer "Ms10a"
    t.integer "Ms10b"
    t.integer "Ms11a"
    t.integer "Ms11b"
    t.integer "Ms14a"
    t.integer "Ms14b"
    t.integer "Ms3a"
    t.integer "Ms3b"
    t.integer "Ms4a"
    t.integer "Ms4b"
    t.integer "Ms8a"
    t.integer "Ms8b"
    t.integer "RW18a"
    t.integer "RW18b"
    t.integer "RW212a"
    t.integer "RW212b"
    t.integer "RW217a"
    t.integer "RW217b"
    t.integer "RW219a"
    t.integer "RW219b"
    t.integer "RW25a"
    t.integer "RW25b"
    t.integer "RW31a"
    t.integer "RW31b"
    t.integer "RW34a"
    t.integer "RW34b"
    t.integer "RW417a"
    t.integer "RW417b"
    t.integer "RW45a"
    t.integer "RW45b"
    t.integer "RW48a"
    t.integer "RW48b"
    t.integer "SAM25a"
    t.integer "SAM25b"
    t.integer "TR2F3a"
    t.integer "TR2F3b"
    t.integer "TR2G5a"
    t.integer "TR2G5b"
    t.integer "TR3A1a"
    t.integer "TR3A1b"
    t.integer "TR3F2a"
    t.integer "TR3F2b"
    t.integer "TR3F7a"
    t.integer "TR3F7b"
    t.integer "TR3G1a"
    t.integer "TR3G1b"
    t.integer "TR3G10a"
    t.integer "TR3G10b"
    t.integer "TR3G11a"
    t.integer "TR3G11b"
    t.integer "TR3G13a"
    t.integer "TR3G13b"
    t.integer "TR3G2a"
    t.integer "TR3G2b"
    t.integer "TR3G5a"
    t.integer "TR3G5b"
    t.integer "TR3G6a"
    t.integer "TR3G6b"
    t.integer "TR3H14a"
    t.integer "TR3H14b"
    t.integer "TR3H4a"
    t.integer "TR3H4b"
    t.integer "TV14a"
    t.integer "TV14b"
    t.integer "TV17a"
    t.integer "TV17b"
    t.integer "TV19a"
    t.integer "TV19b"
    t.integer "TV20a"
    t.integer "TV20b"
  end

  create_table "microsatellite_horizontals_5", :force => true do |t|
    t.integer "project_id"
    t.integer "sample_id"
    t.integer "organism_index"
  end

  create_table "microsatellite_horizontals_6", :force => true do |t|
    t.integer "project_id"
    t.integer "sample_id"
    t.integer "organism_index"
    t.integer "1a"
    t.integer "1b"
  end

  create_table "microsatellite_horizontals_7", :force => true do |t|
    t.integer "project_id"
    t.integer "sample_id"
    t.integer "organism_index"
    t.integer "109a"
    t.integer "109b"
    t.integer "123a"
    t.integer "123b"
    t.integer "172a"
    t.integer "172b"
    t.integer "200a"
    t.integer "200b"
    t.integer "204a"
    t.integer "204b"
    t.integer "225a"
    t.integer "225b"
    t.integer "250a"
    t.integer "250b"
    t.integer "377a"
    t.integer "377b"
  end

  create_table "microsatellite_horizontals_9", :force => true do |t|
    t.integer "project_id"
    t.integer "sample_id"
    t.integer "organism_index"
    t.integer "2a"
    t.integer "2b"
  end

  create_table "microsatellites", :force => true do |t|
    t.integer "sample_id"
    t.integer "project_id"
    t.string  "locus",                :limit => 30
    t.integer "allele1"
    t.integer "allele2"
    t.string  "gel"
    t.string  "well"
    t.boolean "finalResult"
    t.text    "comments"
    t.decimal "allele_1_peak_height",               :precision => 6, :scale => 2
    t.decimal "allele_2_peak_height",               :precision => 6, :scale => 2
    t.integer "locu_id"
  end

  add_index "microsatellites", ["locus"], :name => "index_microsatellites_on_locus"
  add_index "microsatellites", ["allele1"], :name => "index_microsatellites_on_allele1"
  add_index "microsatellites", ["allele2"], :name => "index_microsatellites_on_allele2"
  add_index "microsatellites", ["finalResult"], :name => "index_microsatellites_on_finalResult"
  add_index "microsatellites", ["sample_id"], :name => "index_sample_id"
  add_index "microsatellites", ["project_id"], :name => "index_project_id"

  create_table "mt_dna_final_horizontals", :force => true do |t|
    t.integer "project_id"
    t.integer "organism_id"
    t.string  "organism_code"
    t.integer "haplotype"
  end

  create_table "mt_dna_final_horizontals_1", :force => true do |t|
    t.integer "project_id"
    t.integer "organism_id"
    t.string  "organism_code",                         :limit => 128
    t.string  "1"
    t.string  "Control Region"
    t.string  "Control region, Yoshida et al. (2001)"
    t.string  "cytochrome b"
    t.string  "mtDNA"
  end

  create_table "mt_dna_final_horizontals_12", :force => true do |t|
    t.integer "project_id"
    t.integer "organism_id"
    t.string  "organism_code",                         :limit => 128
    t.string  "Control Region"
    t.string  "Control region, Yoshida et al. (2001)"
    t.string  "cytochrome b"
  end

  create_table "mt_dna_final_horizontals_17", :force => true do |t|
    t.integer "project_id"
    t.integer "organism_id"
    t.string  "organism_code",                         :limit => 128
    t.string  "1"
    t.string  "Control Region"
    t.string  "Control region, Yoshida et al. (2001)"
    t.string  "cytochrome b"
    t.string  "mtDNA"
  end

  create_table "mt_dna_final_horizontals_2", :force => true do |t|
    t.integer "project_id"
    t.integer "organism_id"
    t.string  "organism_code",  :limit => 128
    t.string  "Control Region"
  end

  create_table "mt_dna_final_horizontals_20", :force => true do |t|
    t.integer "project_id"
    t.integer "organism_id"
    t.string  "organism_code",                         :limit => 128
    t.string  "Control Region"
    t.string  "Control region, Yoshida et al. (2001)"
    t.string  "cytochrome b"
    t.string  "mtDNA"
  end

  create_table "mt_dna_final_horizontals_3", :force => true do |t|
    t.integer "project_id"
    t.integer "organism_id"
    t.string  "organism_code",  :limit => 128
    t.string  "Control Region"
    t.string  "cytochrome b"
  end

  create_table "mt_dna_final_horizontals_4", :force => true do |t|
    t.integer "project_id"
    t.integer "organism_id"
    t.string  "organism_code",  :limit => 128
    t.string  "Control Region"
    t.string  "cytochrome b"
  end

  create_table "mt_dna_final_horizontals_5", :force => true do |t|
    t.integer "project_id"
    t.integer "organism_id"
    t.string  "organism_code",  :limit => 128
    t.string  "Control Region"
    t.string  "cytochrome b"
  end

  create_table "mt_dna_final_horizontals_6", :force => true do |t|
    t.integer "project_id"
    t.integer "organism_id"
    t.string  "organism_code",                         :limit => 128
    t.string  "1"
    t.string  "Control Region"
    t.string  "Control region, Yoshida et al. (2001)"
    t.string  "cytochrome b"
    t.string  "mtDNA"
  end

  create_table "mt_dna_final_horizontals_7", :force => true do |t|
    t.integer "project_id"
    t.integer "organism_id"
    t.string  "organism_code",  :limit => 128
    t.string  "Control Region"
    t.string  "cytochrome b"
  end

  create_table "mt_dna_final_horizontals_9", :force => true do |t|
    t.integer "project_id"
    t.integer "organism_id"
    t.string  "organism_code",                         :limit => 128
    t.string  "1"
    t.string  "Control Region"
    t.string  "Control region, Yoshida et al. (2001)"
    t.string  "cytochrome b"
    t.string  "mtDNA"
  end

  create_table "mt_dna_seqs", :force => true do |t|
    t.integer "project_id"
    t.string  "locus"
    t.string  "haplotype"
    t.text    "sequence"
    t.string  "accession",  :limit => 30
  end

  create_table "mt_dnas", :force => true do |t|
    t.integer "sample_id"
    t.integer "project_id"
    t.string  "locus"
    t.string  "haplotype",   :limit => 12
    t.string  "gelNum"
    t.string  "wellNum"
    t.boolean "finalResult"
    t.text    "comments"
    t.integer "locu_id"
  end

  create_table "nats", :force => true do |t|
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "organisms", :force => true do |t|
    t.integer "project_id"
    t.string  "organism_code"
    t.string  "comment"
  end

  create_table "primers", :force => true do |t|
    t.integer "locu_id"
    t.string  "primer"
    t.string  "label"
    t.text    "locus_text"
    t.string  "paper_reference"
    t.string  "primer_sequence"
    t.string  "comments"
    t.date    "date_primer_ordered"
    t.string  "company"
    t.string  "lot_number"
    t.date    "date_primer_received"
    t.string  "room"
    t.string  "freezer"
    t.string  "box_number"
    t.string  "box_type"
    t.string  "lane_inactive"
    t.string  "lane_active"
    t.string  "entered_by"
    t.integer "stock_conc"
    t.integer "alquot_conc"
  end

  create_table "projects", :force => true do |t|
    t.string  "name"
    t.string  "code"
    t.string  "description"
    t.integer "user_id"
    t.boolean "recompile_required"
  end

  create_table "province_state_orig", :primary_key => "PROVINCE_STATE_PK", :force => true do |t|
    t.string  "PROVINCE_STATE_DESC", :limit => 30
    t.integer "COUNTRY_FK"
  end

  add_index "province_state_orig", ["COUNTRY_FK"], :name => "COUNTRY_CODE"
  add_index "province_state_orig", ["COUNTRY_FK"], :name => "CountryProvince_State"

  create_table "queries", :force => true do |t|
    t.integer  "project_id"
    t.string   "name",       :limit => 100
    t.boolean  "draft",                     :default => true
    t.text     "data"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "roles", :force => true do |t|
    t.string "short_role"
    t.string "long_role"
  end

  create_table "sample_non_tissues", :force => true do |t|
    t.integer "organism_id"
    t.integer "project_id"
    t.string  "field_code"
    t.string  "prov"
    t.string  "country"
    t.date    "date_collected"
    t.string  "collected_by"
    t.string  "submitted_by"
    t.date    "date_submitted"
    t.text    "submitter_comments"
    t.string  "received_by"
    t.date    "date_received"
    t.text    "receiver_comments"
    t.float   "latitude"
    t.float   "longitude"
    t.float   "UTM_datum"
    t.string  "locality"
    t.string  "locality_type"
    t.string  "locality_comments"
    t.string  "location_accuracy"
    t.string  "type_lat_long"
  end

  create_table "samples", :force => true do |t|
    t.integer  "project_id"
    t.integer  "organism_id"
    t.string   "organism_index"
    t.string   "field_code"
    t.string   "sample_bc"
    t.string   "plateposition"
    t.string   "platebc"
    t.string   "batch_number"
    t.string   "tissue_type"
    t.string   "storage_medium_text"
    t.string   "country"
    t.string   "province"
    t.datetime "date_collected"
    t.string   "collected_on_day"
    t.string   "collected_on_month"
    t.string   "collected_on_year"
    t.string   "collected_by"
    t.datetime "date_received"
    t.string   "received_by"
    t.text     "receiver_comments"
    t.datetime "date_submitted"
    t.string   "submitted_by"
    t.text     "submitter_comments"
    t.string   "latitude"
    t.string   "longitude"
    t.string   "coordinate_system"
    t.string   "locality"
    t.string   "locality_type_text"
    t.string   "locality_comments"
    t.string   "location_accuracy"
    t.string   "storage_building"
    t.string   "storage_room"
    t.string   "storage_fridge"
    t.string   "storage_box"
    t.string   "xy_position"
    t.boolean  "tissue_remaining"
    t.string   "type_lat_long"
    t.integer  "locality_type_id"
    t.integer  "shippingmaterial_id"
    t.integer  "tissue_type_id"
    t.integer  "province_id"
    t.integer  "storage_medium_id"
    t.integer  "country_id"
    t.integer  "extraction_method_id"
    t.decimal  "true_latitude",               :precision => 18, :scale => 9
    t.decimal  "true_longitude",              :precision => 18, :scale => 9
    t.string   "sample_bc_prv"
    t.string   "shipping_material_txt_prv"
    t.string   "location_measurement_method"
  end

  add_index "samples", ["organism_id"], :name => "index_samples_on_organism_id"
  add_index "samples", ["project_id"], :name => "index_samples_on_project_id"

  create_table "security_settings", :force => true do |t|
    t.integer "project_id"
    t.integer "user_id"
    t.integer "level",      :default => 0
  end

  add_index "security_settings", ["project_id"], :name => "index_security_settings_on_project_id"
  add_index "security_settings", ["user_id"], :name => "index_security_settings_on_user_id"

  create_table "sessions", :force => true do |t|
    t.string   "session_id", :default => "", :null => false
    t.text     "data"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  add_index "sessions", ["session_id"], :name => "index_sessions_on_session_id"
  add_index "sessions", ["updated_at"], :name => "index_sessions_on_updated_at"

  create_table "shippingmaterials", :force => true do |t|
    t.string "medium_short_desc"
    t.string "medium_long_desc"
  end

  create_table "storage_media", :force => true do |t|
    t.string "storage_medium"
  end

  create_table "tissue_types", :force => true do |t|
    t.string "tissue_type"
    t.string "comment"
  end

  create_table "users", :force => true do |t|
    t.integer  "project_id"
    t.string   "login"
    t.string   "email"
    t.string   "crypted_password",          :limit => 40
    t.string   "salt",                      :limit => 40
    t.datetime "created_at"
    t.datetime "updated_at"
    t.string   "remember_token"
    t.datetime "remember_token_expires_at"
    t.boolean  "is_admin",                                :default => false
  end

  create_table "y_chromosome_final_horizontals", :force => true do |t|
    t.integer "project_id"
    t.integer "organism_id"
    t.string  "organism_code"
    t.integer "haplotype"
  end

  create_table "y_chromosome_final_horizontals_1", :force => true do |t|
    t.integer "project_id"
    t.integer "organism_id"
    t.string  "organism_code",     :limit => 128
    t.string  "1"
    t.string  "34a"
    t.string  "34b"
    t.string  "41a"
    t.string  "41b"
    t.string  "many grasshoppers"
    t.string  "Y-Intron"
  end

  create_table "y_chromosome_final_horizontals_12", :force => true do |t|
    t.integer "project_id"
    t.integer "organism_id"
    t.string  "organism_code", :limit => 128
    t.string  "34a"
    t.string  "34b"
    t.string  "41a"
    t.string  "41b"
    t.string  "Y-Intron"
  end

  create_table "y_chromosome_final_horizontals_17", :force => true do |t|
    t.integer "project_id"
    t.integer "organism_id"
    t.string  "organism_code",     :limit => 128
    t.string  "1"
    t.string  "34a"
    t.string  "34b"
    t.string  "41a"
    t.string  "41b"
    t.string  "many grasshoppers"
    t.string  "Y-Intron"
  end

  create_table "y_chromosome_final_horizontals_2", :force => true do |t|
    t.integer "project_id"
    t.integer "organism_id"
    t.string  "organism_code", :limit => 128
  end

  create_table "y_chromosome_final_horizontals_20", :force => true do |t|
    t.integer "project_id"
    t.integer "organism_id"
    t.string  "organism_code",     :limit => 128
    t.string  "34a"
    t.string  "34b"
    t.string  "41a"
    t.string  "41b"
    t.string  "many grasshoppers"
    t.string  "Y-Intron"
  end

  create_table "y_chromosome_final_horizontals_3", :force => true do |t|
    t.integer "project_id"
    t.integer "organism_id"
    t.string  "organism_code", :limit => 128
    t.string  "34a"
    t.string  "34b"
    t.string  "41a"
    t.string  "41b"
    t.string  "Y-Intron"
  end

  create_table "y_chromosome_final_horizontals_4", :force => true do |t|
    t.integer "project_id"
    t.integer "organism_id"
    t.string  "organism_code", :limit => 128
  end

  create_table "y_chromosome_final_horizontals_5", :force => true do |t|
    t.integer "project_id"
    t.integer "organism_id"
    t.string  "organism_code", :limit => 128
    t.string  "34a"
    t.string  "34b"
    t.string  "41a"
    t.string  "41b"
    t.string  "Y-Intron"
  end

  create_table "y_chromosome_final_horizontals_6", :force => true do |t|
    t.integer "project_id"
    t.integer "organism_id"
    t.string  "organism_code",     :limit => 128
    t.string  "1"
    t.string  "34a"
    t.string  "34b"
    t.string  "41a"
    t.string  "41b"
    t.string  "many grasshoppers"
    t.string  "Y-Intron"
  end

  create_table "y_chromosome_final_horizontals_7", :force => true do |t|
    t.integer "project_id"
    t.integer "organism_id"
    t.string  "organism_code", :limit => 128
    t.string  "34a"
    t.string  "34b"
    t.string  "41a"
    t.string  "41b"
    t.string  "Y-Intron"
  end

  create_table "y_chromosome_final_horizontals_9", :force => true do |t|
    t.integer "project_id"
    t.integer "organism_id"
    t.string  "organism_code",     :limit => 128
    t.string  "1"
    t.string  "34a"
    t.string  "34b"
    t.string  "41a"
    t.string  "41b"
    t.string  "many grasshoppers"
    t.string  "Y-Intron"
  end

  create_table "y_chromosome_seqs", :force => true do |t|
    t.integer "sample_id"
    t.integer "project_id"
    t.string  "locus"
    t.string  "allele"
    t.text    "sequence"
    t.string  "accession",  :limit => 30
  end

  create_table "y_chromosomes", :force => true do |t|
    t.integer "sample_id"
    t.integer "project_id"
    t.string  "locus"
    t.string  "haplotype"
    t.string  "gelNum"
    t.string  "wellNum"
    t.boolean "finalResult"
    t.text    "comments"
    t.integer "locu_id"
  end

end
