# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 27) do

  create_table "country_orig", :force => true do |t|
  end

  create_table "dna_results", :force => true do |t|
    t.column "sample_id",          :integer
    t.column "project_id",         :integer
    t.column "prep_number",        :integer
    t.column "extraction_number",  :integer
    t.column "barcode",            :string
    t.column "plate",              :string
    t.column "position",           :string
    t.column "extraction_method",  :string
    t.column "extraction_date",    :date
    t.column "extractor",          :string
    t.column "extractor_comments", :string
    t.column "fluoro_conc",        :float
    t.column "functional_conc",    :float
    t.column "pico_green_conc",    :float
    t.column "storage_building",   :string
    t.column "storage_room",       :string
    t.column "storage_freezer",    :string
    t.column "storage_box",        :string
    t.column "xy_position",        :string
    t.column "dna_remaining",      :boolean
  end

  create_table "dynamic_attribute_values", :force => true do |t|
    t.column "dynamic_attribute_id", :integer
    t.column "owner_type",           :string
    t.column "owner_id",             :integer
    t.column "integer_value",        :integer
    t.column "float_value",          :integer,  :limit => 10, :precision => 10, :scale => 0
    t.column "text_value",           :text
    t.column "date_value",           :date
    t.column "timestamp_value",      :datetime
  end

  add_index "dynamic_attribute_values", ["dynamic_attribute_id"], :name => "index_dynamic_attribute_values_on_dynamic_attribute_id"
  add_index "dynamic_attribute_values", ["owner_id"], :name => "index_dynamic_attribute_values_on_owner_id"
  add_index "dynamic_attribute_values", ["owner_type"], :name => "index_dynamic_attribute_values_on_owner_type"
  add_index "dynamic_attribute_values", ["owner_type", "owner_id"], :name => "index_dynamic_attribute_values_on_owner_type_and_owner_id"

  create_table "dynamic_attributes", :force => true do |t|
    t.column "name",             :string
    t.column "dynamic_type_id",  :integer
    t.column "dynamic_class_id", :integer
    t.column "scoper_type",      :string
    t.column "scoper_id",        :integer
    t.column "owner_type",       :string
  end

  add_index "dynamic_attributes", ["name"], :name => "index_dynamic_attributes_on_name"
  add_index "dynamic_attributes", ["dynamic_type_id"], :name => "index_dynamic_attributes_on_dynamic_type_id"
  add_index "dynamic_attributes", ["dynamic_class_id"], :name => "index_dynamic_attributes_on_dynamic_class_id"
  add_index "dynamic_attributes", ["owner_type"], :name => "index_dynamic_attributes_on_owner_type"

  create_table "dynamic_classes", :force => true do |t|
    t.column "name", :string
  end

  add_index "dynamic_classes", ["name"], :name => "index_dynamic_classes_on_name"

  create_table "dynamic_types", :force => true do |t|
    t.column "name",            :string
    t.column "stored_in_field", :string
    t.column "description",     :string
  end

  add_index "dynamic_types", ["name"], :name => "index_dynamic_types_on_name"

  create_table "extraction_methods", :force => true do |t|
    t.column "extraction_method_name",        :string
    t.column "extraction_method_description", :string
  end

  create_table "genders", :force => true do |t|
    t.column "sample_id",   :integer
    t.column "project_id",  :integer
    t.column "gender",      :string
    t.column "gelNum",      :string
    t.column "wellNum",     :string
    t.column "finalResult", :boolean
  end

  create_table "locality_types", :force => true do |t|
    t.column "locality_type_name", :string
    t.column "locality_type_desc", :string
  end

  create_table "mhc_seqs", :force => true do |t|
    t.column "project_id", :integer
    t.column "locus",      :string
    t.column "allele",     :string
    t.column "sequence",   :text
  end

  create_table "mhcs", :force => true do |t|
    t.column "sample_id",   :integer
    t.column "project_id",  :integer
    t.column "locus",       :string
    t.column "allele1",     :string
    t.column "allele2",     :string
    t.column "gelNum",      :string
    t.column "wellNum",     :string
    t.column "finalResult", :boolean
  end

  create_table "microsatellite_horizontals", :force => true do |t|
    t.column "project_id",    :integer
    t.column "sample_id",     :integer
    t.column "organism_code", :integer
    t.column "org_sample",    :integer
    t.column "allelea",       :integer
    t.column "alleleb",       :integer
  end

  create_table "microsatellite_horizontals_1", :force => true do |t|
    t.column "project_id",        :integer
    t.column "sample_id",         :integer
    t.column "organism_code",     :integer
    t.column "org_sample",        :integer
    t.column "extraction_number", :integer
    t.column "EV1Pma",            :integer
    t.column "EV1Pmb",            :integer
    t.column "EV37Mna",           :integer
    t.column "EV37Mnb",           :integer
    t.column "GATA028a",          :integer
    t.column "GATA028b",          :integer
    t.column "GT023a",            :integer
    t.column "GT023b",            :integer
    t.column "GT271a",            :integer
    t.column "GT271b",            :integer
    t.column "IGFa",              :integer
    t.column "IGFb",              :integer
    t.column "RW18a",             :integer
    t.column "RW18b",             :integer
    t.column "RW212a",            :integer
    t.column "RW212b",            :integer
    t.column "RW217a",            :integer
    t.column "RW217b",            :integer
    t.column "RW219a",            :integer
    t.column "RW219b",            :integer
    t.column "RW25a",             :integer
    t.column "RW25b",             :integer
    t.column "RW31a",             :integer
    t.column "RW31b",             :integer
    t.column "RW34a",             :integer
    t.column "RW34b",             :integer
    t.column "RW417a",            :integer
    t.column "RW417b",            :integer
    t.column "RW45a",             :integer
    t.column "RW45b",             :integer
    t.column "RW48a",             :integer
    t.column "RW48b",             :integer
    t.column "SAM25a",            :integer
    t.column "SAM25b",            :integer
    t.column "TR2F3a",            :integer
    t.column "TR2F3b",            :integer
    t.column "TR2G5a",            :integer
    t.column "TR2G5b",            :integer
    t.column "TR3A1a",            :integer
    t.column "TR3A1b",            :integer
    t.column "TR3F2a",            :integer
    t.column "TR3F2b",            :integer
    t.column "TR3F7a",            :integer
    t.column "TR3F7b",            :integer
    t.column "TR3G1a",            :integer
    t.column "TR3G1b",            :integer
    t.column "TR3G10a",           :integer
    t.column "TR3G10b",           :integer
    t.column "TR3G11a",           :integer
    t.column "TR3G11b",           :integer
    t.column "TR3G13a",           :integer
    t.column "TR3G13b",           :integer
    t.column "TR3G2a",            :integer
    t.column "TR3G2b",            :integer
    t.column "TR3G5a",            :integer
    t.column "TR3G5b",            :integer
    t.column "TR3G6a",            :integer
    t.column "TR3G6b",            :integer
    t.column "TR3H14a",           :integer
    t.column "TR3H14b",           :integer
    t.column "TR3H4a",            :integer
    t.column "TR3H4b",            :integer
    t.column "TV14a",             :integer
    t.column "TV14b",             :integer
    t.column "TV17a",             :integer
    t.column "TV17b",             :integer
    t.column "TV19a",             :integer
    t.column "TV19b",             :integer
    t.column "TV20a",             :integer
    t.column "TV20b",             :integer
  end

  create_table "microsatellite_horizontals_2", :force => true do |t|
    t.column "project_id",        :integer
    t.column "sample_id",         :integer
    t.column "organism_code",     :integer
    t.column "org_sample",        :integer
    t.column "extraction_number", :integer
    t.column "EV1Pma",            :integer
    t.column "EV1Pmb",            :integer
    t.column "EV37Mna",           :integer
    t.column "EV37Mnb",           :integer
    t.column "GATA028a",          :integer
    t.column "GATA028b",          :integer
    t.column "GT023a",            :integer
    t.column "GT023b",            :integer
    t.column "GT271a",            :integer
    t.column "GT271b",            :integer
    t.column "IGFa",              :integer
    t.column "IGFb",              :integer
    t.column "RW18a",             :integer
    t.column "RW18b",             :integer
    t.column "RW212a",            :integer
    t.column "RW212b",            :integer
    t.column "RW217a",            :integer
    t.column "RW217b",            :integer
    t.column "RW219a",            :integer
    t.column "RW219b",            :integer
    t.column "RW25a",             :integer
    t.column "RW25b",             :integer
    t.column "RW31a",             :integer
    t.column "RW31b",             :integer
    t.column "RW34a",             :integer
    t.column "RW34b",             :integer
    t.column "RW417a",            :integer
    t.column "RW417b",            :integer
    t.column "RW45a",             :integer
    t.column "RW45b",             :integer
    t.column "RW48a",             :integer
    t.column "RW48b",             :integer
    t.column "SAM25a",            :integer
    t.column "SAM25b",            :integer
    t.column "TR2F3a",            :integer
    t.column "TR2F3b",            :integer
    t.column "TR2G5a",            :integer
    t.column "TR2G5b",            :integer
    t.column "TR3A1a",            :integer
    t.column "TR3A1b",            :integer
    t.column "TR3F2a",            :integer
    t.column "TR3F2b",            :integer
    t.column "TR3F7a",            :integer
    t.column "TR3F7b",            :integer
    t.column "TR3G1a",            :integer
    t.column "TR3G1b",            :integer
    t.column "TR3G10a",           :integer
    t.column "TR3G10b",           :integer
    t.column "TR3G11a",           :integer
    t.column "TR3G11b",           :integer
    t.column "TR3G13a",           :integer
    t.column "TR3G13b",           :integer
    t.column "TR3G2a",            :integer
    t.column "TR3G2b",            :integer
    t.column "TR3G5a",            :integer
    t.column "TR3G5b",            :integer
    t.column "TR3G6a",            :integer
    t.column "TR3G6b",            :integer
    t.column "TR3H14a",           :integer
    t.column "TR3H14b",           :integer
    t.column "TR3H4a",            :integer
    t.column "TR3H4b",            :integer
    t.column "TV14a",             :integer
    t.column "TV14b",             :integer
    t.column "TV17a",             :integer
    t.column "TV17b",             :integer
    t.column "TV19a",             :integer
    t.column "TV19b",             :integer
    t.column "TV20a",             :integer
    t.column "TV20b",             :integer
  end

  create_table "microsatellite_organism_horizontals", :force => true do |t|
    t.column "project_id",    :integer
    t.column "organism_id",   :integer
    t.column "organism_code", :integer
    t.column "allelea",       :integer
    t.column "alleleb",       :integer
  end

  create_table "microsatellite_organism_horizontals_1", :force => true do |t|
    t.column "project_id",        :integer
    t.column "organism_id",       :integer
    t.column "organism_code",     :integer
    t.column "extraction_number", :integer
    t.column "EV1Pma",            :integer
    t.column "EV1Pmb",            :integer
    t.column "EV37Mna",           :integer
    t.column "EV37Mnb",           :integer
    t.column "GATA028a",          :integer
    t.column "GATA028b",          :integer
    t.column "GT023a",            :integer
    t.column "GT023b",            :integer
    t.column "GT271a",            :integer
    t.column "GT271b",            :integer
    t.column "IGFa",              :integer
    t.column "IGFb",              :integer
    t.column "RW18a",             :integer
    t.column "RW18b",             :integer
    t.column "RW212a",            :integer
    t.column "RW212b",            :integer
    t.column "RW217a",            :integer
    t.column "RW217b",            :integer
    t.column "RW219a",            :integer
    t.column "RW219b",            :integer
    t.column "RW25a",             :integer
    t.column "RW25b",             :integer
    t.column "RW31a",             :integer
    t.column "RW31b",             :integer
    t.column "RW34a",             :integer
    t.column "RW34b",             :integer
    t.column "RW417a",            :integer
    t.column "RW417b",            :integer
    t.column "RW45a",             :integer
    t.column "RW45b",             :integer
    t.column "RW48a",             :integer
    t.column "RW48b",             :integer
    t.column "SAM25a",            :integer
    t.column "SAM25b",            :integer
    t.column "TR2F3a",            :integer
    t.column "TR2F3b",            :integer
    t.column "TR2G5a",            :integer
    t.column "TR2G5b",            :integer
    t.column "TR3A1a",            :integer
    t.column "TR3A1b",            :integer
    t.column "TR3F2a",            :integer
    t.column "TR3F2b",            :integer
    t.column "TR3F7a",            :integer
    t.column "TR3F7b",            :integer
    t.column "TR3G1a",            :integer
    t.column "TR3G1b",            :integer
    t.column "TR3G10a",           :integer
    t.column "TR3G10b",           :integer
    t.column "TR3G11a",           :integer
    t.column "TR3G11b",           :integer
    t.column "TR3G13a",           :integer
    t.column "TR3G13b",           :integer
    t.column "TR3G2a",            :integer
    t.column "TR3G2b",            :integer
    t.column "TR3G5a",            :integer
    t.column "TR3G5b",            :integer
    t.column "TR3G6a",            :integer
    t.column "TR3G6b",            :integer
    t.column "TR3H14a",           :integer
    t.column "TR3H14b",           :integer
    t.column "TR3H4a",            :integer
    t.column "TR3H4b",            :integer
    t.column "TV14a",             :integer
    t.column "TV14b",             :integer
    t.column "TV17a",             :integer
    t.column "TV17b",             :integer
    t.column "TV19a",             :integer
    t.column "TV19b",             :integer
    t.column "TV20a",             :integer
    t.column "TV20b",             :integer
  end

  create_table "microsatellite_organism_horizontals_2", :force => true do |t|
    t.column "project_id",        :integer
    t.column "organism_id",       :integer
    t.column "organism_code",     :integer
    t.column "extraction_number", :integer
    t.column "EV1Pma",            :integer
    t.column "EV1Pmb",            :integer
    t.column "EV37Mna",           :integer
    t.column "EV37Mnb",           :integer
    t.column "GATA028a",          :integer
    t.column "GATA028b",          :integer
    t.column "GT023a",            :integer
    t.column "GT023b",            :integer
    t.column "GT271a",            :integer
    t.column "GT271b",            :integer
    t.column "IGFa",              :integer
    t.column "IGFb",              :integer
    t.column "RW18a",             :integer
    t.column "RW18b",             :integer
    t.column "RW212a",            :integer
    t.column "RW212b",            :integer
    t.column "RW217a",            :integer
    t.column "RW217b",            :integer
    t.column "RW219a",            :integer
    t.column "RW219b",            :integer
    t.column "RW25a",             :integer
    t.column "RW25b",             :integer
    t.column "RW31a",             :integer
    t.column "RW31b",             :integer
    t.column "RW34a",             :integer
    t.column "RW34b",             :integer
    t.column "RW417a",            :integer
    t.column "RW417b",            :integer
    t.column "RW45a",             :integer
    t.column "RW45b",             :integer
    t.column "RW48a",             :integer
    t.column "RW48b",             :integer
    t.column "SAM25a",            :integer
    t.column "SAM25b",            :integer
    t.column "TR2F3a",            :integer
    t.column "TR2F3b",            :integer
    t.column "TR2G5a",            :integer
    t.column "TR2G5b",            :integer
    t.column "TR3A1a",            :integer
    t.column "TR3A1b",            :integer
    t.column "TR3F2a",            :integer
    t.column "TR3F2b",            :integer
    t.column "TR3F7a",            :integer
    t.column "TR3F7b",            :integer
    t.column "TR3G1a",            :integer
    t.column "TR3G1b",            :integer
    t.column "TR3G10a",           :integer
    t.column "TR3G10b",           :integer
    t.column "TR3G11a",           :integer
    t.column "TR3G11b",           :integer
    t.column "TR3G13a",           :integer
    t.column "TR3G13b",           :integer
    t.column "TR3G2a",            :integer
    t.column "TR3G2b",            :integer
    t.column "TR3G5a",            :integer
    t.column "TR3G5b",            :integer
    t.column "TR3G6a",            :integer
    t.column "TR3G6b",            :integer
    t.column "TR3H14a",           :integer
    t.column "TR3H14b",           :integer
    t.column "TR3H4a",            :integer
    t.column "TR3H4b",            :integer
    t.column "TV14a",             :integer
    t.column "TV14b",             :integer
    t.column "TV17a",             :integer
    t.column "TV17b",             :integer
    t.column "TV19a",             :integer
    t.column "TV19b",             :integer
    t.column "TV20a",             :integer
    t.column "TV20b",             :integer
  end

  create_table "microsatellites", :force => true do |t|
    t.column "sample_id",   :integer
    t.column "project_id",  :integer
    t.column "locus",       :string
    t.column "allele1",     :string
    t.column "allele2",     :string
    t.column "gel",         :string
    t.column "well",        :string
    t.column "finalResult", :boolean
  end

  add_index "microsatellites", ["sample_id", "project_id", "locus"], :name => "Index_2"
  add_index "microsatellites", ["locus"], :name => "index_microsatellites_on_locus"
  add_index "microsatellites", ["allele1"], :name => "index_microsatellites_on_allele1"
  add_index "microsatellites", ["allele2"], :name => "index_microsatellites_on_allele2"
  add_index "microsatellites", ["finalResult"], :name => "index_microsatellites_on_finalResult"

  create_table "microsatellites_project_001_by_sample", :force => true do |t|
    t.column "project_id",        :string,  :limit => 50
    t.column "organism_code",     :float
    t.column "org_Sample",        :float
    t.column "extraction_number", :float
    t.column "EV1Pma",            :float
    t.column "EVPm1b",            :float
    t.column "EV37Mna",           :float
    t.column "EV37Mnb",           :float
    t.column "GATA028a",          :float
    t.column "GATA028b",          :float
    t.column "GT023a",            :float
    t.column "GT023b",            :float
    t.column "GT271a",            :float
    t.column "GT271b",            :float
    t.column "IGFa",              :float
    t.column "IGFb",              :float
    t.column "RW18a",             :float
    t.column "RW18b",             :float
    t.column "RW25a",             :float
    t.column "RW25b",             :float
    t.column "RW31a",             :float
    t.column "RW31b",             :float
    t.column "RW34a",             :float
    t.column "RW34b",             :float
    t.column "RW45a",             :float
    t.column "RW45b",             :float
    t.column "RW48a",             :float
    t.column "RW48b",             :float
    t.column "RW212a",            :float
    t.column "RW212b",            :float
    t.column "RW217a",            :float
    t.column "RW217b",            :float
    t.column "RW219a",            :float
    t.column "RW219b",            :float
    t.column "RW417a",            :float
    t.column "RW417b",            :float
    t.column "SAM25a",            :float
    t.column "SAM25b",            :float
    t.column "TR2F3a",            :float
    t.column "TR2F3b",            :float
    t.column "TR2G5a",            :float
    t.column "TR2G5b",            :float
    t.column "TR3A1a",            :float
    t.column "TR3A1b",            :float
    t.column "TR3F2a",            :float
    t.column "TR3F2b",            :float
    t.column "TR3F7a",            :float
    t.column "TR3F7b",            :float
    t.column "TR3G1a",            :float
    t.column "TR3G1b",            :float
    t.column "TR3G2a",            :float
    t.column "TR3G2b",            :float
    t.column "TR3G5a",            :float
    t.column "TR3G5b",            :float
    t.column "TR3G6a",            :float
    t.column "TR3G6b",            :float
    t.column "TR3G10a",           :float
    t.column "TR3G10b",           :float
    t.column "TR3G11a",           :float
    t.column "TR3G11b",           :float
    t.column "TR3G13a",           :float
    t.column "TR3G13b",           :float
    t.column "TR3H4a",            :float
    t.column "TR3H4b",            :float
    t.column "TR3H14a",           :float
    t.column "TR3H14b",           :float
    t.column "TV14a",             :float
    t.column "TV14b",             :float
    t.column "TV17a",             :float
    t.column "TV17b",             :float
    t.column "TV19a",             :float
    t.column "TV19b",             :float
    t.column "TV20a",             :float
    t.column "TV20b",             :float
    t.column "sample_id",         :integer
  end

  add_index "microsatellites_project_001_by_sample", ["project_id"], :name => "project_id"

  create_table "mt_dna_seqs", :force => true do |t|
    t.column "project_id", :integer
    t.column "locus",      :string
    t.column "haplotype",  :string
    t.column "sequence",   :text
  end

  create_table "mt_dnas", :force => true do |t|
    t.column "sample_id",   :integer
    t.column "project_id",  :integer
    t.column "locus",       :string
    t.column "haplotype",   :string
    t.column "gelNum",      :string
    t.column "wellNum",     :string
    t.column "finalResult", :boolean
  end

  create_table "organisms", :force => true do |t|
    t.column "project_id",    :integer
    t.column "organism_code", :string
    t.column "comment",       :string
  end

  create_table "projects", :force => true do |t|
    t.column "name",        :string
    t.column "code",        :string
    t.column "description", :string
    t.column "user_id",     :integer
  end

  create_table "province_state_orig", :id => false, :force => true do |t|
    t.column "PROVINCE_STATE_PK",   :string,  :limit => 2,  :default => "", :null => false
    t.column "PROVINCE_STATE_DESC", :string,  :limit => 30
    t.column "COUNTRY_FK",          :integer
  end

  add_index "province_state_orig", ["COUNTRY_FK"], :name => "COUNTRY_CODE"
  add_index "province_state_orig", ["COUNTRY_FK"], :name => "CountryProvince_State"

  create_table "sample_non_tissues", :force => true do |t|
    t.column "organism_id",        :integer
    t.column "project_id",         :integer
    t.column "field_code",         :string
    t.column "prov",               :string
    t.column "country",            :string
    t.column "date_collected",     :date
    t.column "collected_by",       :string
    t.column "submitted_by",       :string
    t.column "date_submitted",     :date
    t.column "submitter_comments", :text
    t.column "received_by",        :string
    t.column "date_received",      :date
    t.column "receiver_comments",  :text
    t.column "latitude",           :float
    t.column "longitude",          :float
    t.column "UTM_datum",          :float
    t.column "locality",           :string
    t.column "locality_type",      :string
    t.column "locality_comments",  :string
    t.column "location_accuracy",  :string
    t.column "type_lat_long",      :string
  end

  create_table "samples", :force => true do |t|
    t.column "project_id",           :integer
    t.column "organism_id",          :integer
    t.column "organism_code",        :string
    t.column "org_sample",           :string
    t.column "tubebc",               :string
    t.column "platebc",              :string
    t.column "plateposition",        :string
    t.column "field_code",           :string
    t.column "batch_number",         :string
    t.column "tissue_type",          :string
    t.column "storage_medium",       :string
    t.column "country",              :string
    t.column "province",             :string
    t.column "date_collected",       :datetime
    t.column "collected_on_day",     :integer
    t.column "collected_on_month",   :integer
    t.column "collected_on_year",    :integer
    t.column "collected_by",         :string
    t.column "date_received",        :datetime
    t.column "received_by",          :string
    t.column "receiver_comments",    :text
    t.column "date_submitted",       :datetime
    t.column "submitted_by",         :string
    t.column "submitter_comments",   :text
    t.column "latitude",             :float
    t.column "longitude",            :float
    t.column "UTM_datum",            :float
    t.column "locality",             :string
    t.column "locality_type",        :string
    t.column "locality_comments",    :string
    t.column "location_accuracy",    :string
    t.column "storage_building",     :string
    t.column "storage_room",         :string
    t.column "storage_fridge",       :string
    t.column "storage_box",          :string
    t.column "xy_position",          :string
    t.column "tissue_remaining",     :boolean
    t.column "type_lat_long",        :string
    t.column "locality_type_id",     :integer
    t.column "shippingmaterial_id",  :integer
    t.column "tissue_type_id",       :integer
    t.column "province_id",          :integer
    t.column "storage_medium_id",    :integer
    t.column "country_id",           :integer
    t.column "extraction_method_id", :integer
  end

  add_index "samples", ["organism_id"], :name => "index_samples_on_organism_id"
  add_index "samples", ["organism_code"], :name => "index_samples_on_organism_code"
  add_index "samples", ["project_id"], :name => "index_samples_on_project_id"

  create_table "security_settings", :force => true do |t|
    t.column "project_id", :integer
    t.column "user_id",    :integer
    t.column "level",      :integer, :default => 0
  end

  add_index "security_settings", ["project_id"], :name => "index_security_settings_on_project_id"
  add_index "security_settings", ["user_id"], :name => "index_security_settings_on_user_id"

  create_table "shippingmaterials", :force => true do |t|
    t.column "medium_short_desc", :string
    t.column "medium_long_desc",  :string
  end

  create_table "tissue_types", :force => true do |t|
    t.column "tissue_type", :string
    t.column "comment",     :string
  end

  create_table "users", :force => true do |t|
    t.column "project_id",                :integer
    t.column "login",                     :string
    t.column "email",                     :string
    t.column "crypted_password",          :string,   :limit => 40
    t.column "salt",                      :string,   :limit => 40
    t.column "created_at",                :datetime
    t.column "updated_at",                :datetime
    t.column "remember_token",            :string
    t.column "remember_token_expires_at", :datetime
  end

  create_table "y_chromosome_seqs", :force => true do |t|
    t.column "sample_id",  :integer
    t.column "project_id", :integer
    t.column "locus",      :string
    t.column "haplotype",  :string
    t.column "sequence",   :text
  end

  create_table "y_chromosomes", :force => true do |t|
    t.column "sample_id",   :integer
    t.column "project_id",  :integer
    t.column "locus",       :string
    t.column "haplotype",   :string
    t.column "gelNum",      :string
    t.column "wellNum",     :string
    t.column "finalResult", :boolean
  end

end
