#!/usr/bin/env ruby
#require File.dirname(__FILE__) + '/../config/boot'
# require 'thread'
#require File.expand_path('../../config/boot',  __FILE__)

$: << File.dirname(__FILE__) + '../..'
require File.expand_path('../../config/boot', __FILE__)

require 'commands/server'

