class CreateSightings < ActiveRecord::Migration
  def self.up
    create_table "sightings", :force => true do |t|
    t.integer  "survey_id"
    t.datetime "sighting_date"
    t.datetime "sighting_time"
    t.string   "survey_vessel"
    t.boolean    "clear"
    t.boolean    "hazy"
    t.boolean    "clouds"
    t.boolean    "overcast"
    t.boolean    "glare"
    t.boolean    "sunny"
    t.boolean    "foggy"
    t.boolean    "mainly_cloudy"
    t.boolean    "rain"
    t.string   "latitude"
    t.string   "longitude"
    t.string   "sighting_by"
    t.string   "speed_min"
    t.string   "speed_max"
    t.string   "bearing"
    t.string   "ss"
    t.float    "depth"
    t.string   "sst"
    t.string   "sal"
    t.string   "angle"
    t.string   "dist"
    t.float    "group_max"
    t.float    "group_min"
    t.float    "group_best"
    t.string   "mother_calf_pairs"
    t.string   "dist_min"
    t.string   "dolphin_speed"
    t.string   "group_comments"
    t.boolean    "logging"
    t.boolean    "slow_swim"
    t.boolean    "fast_swim"
    t.boolean    "porpoising"
    t.boolean    "chasing"
    t.boolean    "breaching"
    t.boolean    "surfing"
    t.boolean    "fluke_up"
    t.boolean    "back_arch"
    t.boolean    "bow_ride"
    t.boolean    "stern_ride"
    t.boolean    "synch"
    t.boolean    "mostly_synch"
    t.boolean    "asynch"
    t.boolean    "unidir"
    t.boolean    "mostly_unidir"
    t.boolean    "multidir"
    t.boolean    "loose_group"
    t.boolean    "adult_pairs"
    t.boolean    "subgroups"
    t.boolean    "tight_group"
    t.string   "structure_comments"
    t.boolean    "resting"
    t.boolean    "travelling"
    t.boolean    "feeding"
    t.boolean    "play"
    t.boolean    "mating_sexual"
    t.boolean    "aggression"
    t.boolean    "prey_mouth"
    t.boolean    "prey_water"
    t.boolean    "prey_fleeing"
    t.boolean    "prey_sonar"
    t.boolean    "driftnet"
    t.boolean    "sink_gillnets"
    t.boolean    "trawl"
    t.boolean    "pole_fishing"
    t.boolean    "commercial"
    t.string   "vessel_comments"
    t.boolean    "assoc_fish"
    t.boolean    "assoc_seabirds"
    t.boolean    "assoc_upwell"
    t.boolean    "assoc_weed"
    t.boolean    "assoc_debris"
    t.string   "association_comments"
    t.string   "sonar"
    t.string   "scy_cam"
    t.string   "photo_comments"
    t.string   "general_comments"
    t.integer    "id_number"
    t.string   "id_text"
    t.string   "id_comments"
    t.timestamps
    end

    add_index "sightings", ["id_number"], :name => "ID_number"
    add_index "sightings", ["id_comments"], :name => "ID_comments"
    add_index "sightings", ["id_text"], :name => "ID_text"
  end

  def self.down
    drop_table :sightings
  end
end
