class CreateSightings < ActiveRecord::Migration
  def self.up
    create_table "sightings", :force => true do |t|
    t.integer  "survey_id"
    t.datetime "Date"
    t.datetime "Time"
    t.string   "survey_vessel"
    t.boolean    "Clear"
    t.boolean    "Hazy"
    t.boolean    "Clouds"
    t.boolean    "Overcast"
    t.boolean    "Glare"
    t.boolean    "Sunny"
    t.boolean    "Foggy"
    t.boolean    "Mainly_cloudy"
    t.boolean    "Rain"
    t.string   "Latitude"
    t.string   "Longitude"
    t.string   "Sighting_By"
    t.string   "Speed_min"
    t.string   "Speed_max"
    t.string   "Bearing"
    t.string   "SS"
    t.float    "Depth"
    t.string   "SST"
    t.string   "Sal"
    t.string   "Angle"
    t.string   "Dist"
    t.float    "group_max"
    t.float    "group_min"
    t.float    "group_best"
    t.string   "mother_calf_pairs"
    t.string   "dist_min"
    t.string   "dolphin_speed"
    t.string   "group_comments"
    t.boolean    "Logging"
    t.boolean    "slow_swim"
    t.boolean    "fast_swim"
    t.boolean    "Porpoising"
    t.boolean    "Chasing"
    t.boolean    "Breaching"
    t.boolean    "Surfing"
    t.boolean    "Fluke_up"
    t.boolean    "back_arch"
    t.boolean    "bow_ride"
    t.boolean    "stern_ride"
    t.boolean    "Synch"
    t.boolean    "Mostly_synch"
    t.boolean    "Asynch"
    t.boolean    "Unidir"
    t.boolean    "Mostly_Unidir"
    t.boolean    "Multidir"
    t.boolean    "loose_group"
    t.boolean    "adult_pairs"
    t.boolean    "Subgroups"
    t.boolean    "tight_group"
    t.string   "structure_comments"
    t.boolean    "Resting"
    t.boolean    "Travelling"
    t.boolean    "Feeding"
    t.boolean    "Play"
    t.boolean    "Mating_Sexual"
    t.boolean    "Aggression"
    t.boolean    "prey_mouth"
    t.boolean    "prey_water"
    t.boolean    "prey_fleeing"
    t.boolean    "prey_sonar"
    t.boolean    "Driftnet"
    t.boolean    "Sink_gillnets"
    t.boolean    "Trawl"
    t.boolean    "Pole_fishing"
    t.boolean    "Commercial"
    t.string   "Vessel_comments"
    t.boolean    "assoc_fish"
    t.boolean    "assoc_seabirds"
    t.boolean    "assoc_upwell"
    t.boolean    "assoc_weed"
    t.boolean    "assoc_debris"
    t.string   "association_comments"
    t.string   "Sonar"
    t.string   "SCY"
    t.string   "Colour_Letter_Code"
    t.string   "general_comments"
    t.integer    "ID_number"
    t.string   "ID_text"
    t.string   "ID_comments"
    t.timestamps
    end

    add_index "sightings", ["ID_number"], :name => "ID_number"
    add_index "sightings", ["Colour_Letter_Code"], :name => "Colour_Letter_Code"
    add_index "sightings", ["ID_comments"], :name => "ID_comments"
    add_index "sightings", ["ID_text"], :name => "ID_text"
  end

  def self.down
    drop_table :sightings
  end
end
